### ISSUE TITLE
Avoid relative links between User / Programmers / Admin Guides and README

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1137]
In the guides content there are some links which are relative and as the README is a separate animal they will fail. Consider convert them to absolute links or consider alternative ways of content structuring.

**Comment by fgalan** [comment]
The problem with absolute links is that they cannot be relative to branches and that develop branch cannot be used as absolute, as that will break the self-contaiment of documentation in release branches.

**Comment by jmcanterafonseca** [comment]
good point. then probably we would need to drop links, wouldn't we?

2015-08-10 10:34 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
> good point. then probably we would need to drop links, wouldn't we?

I think that dropping links at all is not a good idea. Links are a very useful tool to relate topics among different sections in the documentation. Removing links at all will make the documentation MUCH difficult to read.

Maybe some "preparation" step could be run by mkdocs? I.e. instead of eating the .md directly, run some replacement script (sed-link) to adjust links. Unfortunatelly, I don't know enough of readthedocs to figure out how that could be implemented.

**Comment by jmcanterafonseca** [comment]
We could do it without overcomplicating it by restructuring content. The README should be an overview document and manuals should be detailed content. So it is logical to think that README can point to Guides but not the contrary as Guides >> README

**Comment by fgalan** [comment]
Thus, to check if I'm understanding properly... The problem is *only* in links from the .md inside manual to the README.md? 

More explictely, the following cases are not problematic:

* README.md -> .md in the manuals
* From one .md in the manuals to other .md in the manuals.

**Comment by fgalan** [comment]
After moving some sections from README.md to manuals, this problem should no longer happend. @jmcanterafonseca could you have a look to it and close the issue if you find it ok, please?

**Comment by jmcanterafonseca** [comment]
fixed and closed
