### ISSUE TITLE
[BUG] "Parse Error" leftover  in decription message (ERRORS)

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1200]
| error       | BadRequest      
----------------------------------------------------------------------------------------------                             
      | description | Parse Error (Invalid characters in entity type)
      | description | Parse Error (Invalid characters in entity id) 
      | description | Parse Error (Invalid characters in attribute name) 
      | description | Parse Error (Invalid characters in attribute value) 
      | description | Parse Error (Invalid characters in attribute value) 
      | description | Parse Error (Invalid characters in metadata name) 
      | description | Parse Error (missing metadata value) 
      | description | Parse Error (Invalid characters in metadata value) 
      | description | Parse Error (Invalid characters in metadata type)

**Comment by fgalan** [comment]
In order to solve this issue, the "Parse Error (...)" should be removed, so the description message only includes for example "Invalid characters in entity type". This is needed due to ParseError is an error in NGSIv2 (see http://telefonicaid.github.io/fiware-orion/api/v2/) reserved for error in the JSON parsint itself, so it is not a good idea to reuse the same words for BadRequest errors.

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/fiware-orion/pull/1236. @iariasleon please have a look and close the issue if you find it ok, please.

**Comment by iariasleon** [comment]
LGTM
