### ISSUE TITLE
APIv2: geo-queries

### ISSUE THREAD

**Issue by tobiasjacobs** [telefonicaid/fiware-orion#1462]
In the descriptions of the geographical queries in is unclear against what they are matched. 

Possibilities I see to defined coordinates are:
a) as specific attributes with predefined names
b) as specific registration metadata with predefined name/type
c) completely up to the NGSI system
d) user-defined, i.e. the relevant attributes for the coordinates are specified as part of the geo-query expression.

**Comment by jmcanterafonseca** [comment]
@tobiasjacobs thanks for bringing up this important issue. 

First of all I think there should not be any limitation in how users convey spatial dimensions to their NGSI entities, so that the spatial dimension of an entity could be be conveyed using different attributes and different geometries, not only points. So ideally the implementation should be able to determine the most accurate / precise (i.e point against polygon, etc.) location known for an entity and use that location to resolve geo-queries. 

Nonetheless, the implementation must support certain location syntaxes such as the proposed geo:point micro-syntax or GeoJSON object itself. That will allow the implementation to infer what are the attributes which are providing geospatial information and use them when resolving GeoQueries. 

If no hint is provided then the implementation will resolve a query by using the attribute value which provides the most accurate location data and resolution. However I think we are going to need a mechanism to force using a certain location attribute when resolving a query, although that will be only needed for very particular use cases, and probably not need to be part of the Simple Query ?q= interface.

**Comment by fgalan** [comment]
Actually, d) has two posibilities:

* d.1) user defined at entity creation/update time, e.g. using a predefined metadata to "mark" the attribute that means location (this is the approach that NGSIv1 uses)
* d.2) user defined at query time, specifying in the query the attribute tu use to "mark" location (I think this is the one in the original @tobiasjacobs message)

Before goint to complex appraoches as the ones that @jmcanterafonseca proposes (i.e. using GeoJSON object to define entity location) I'll try at least to reach a minimum support level, simple enought to be easily implementable. Probably that should be the minimum level to introduce in the "core" APIv2 spec.

**Comment by tobiasjacobs** [comment]
I was referring to d.2), but d.1) is also another option of course.

A standardized way to express the locations of entities as specific attributes could be part of an "NGSI base ontology".

**Comment by tobiasjacobs** [comment]
the new proposal with issue #1516 (https://github.com/telefonicaid/fiware-orion/issues/1516) is related to this.

**Comment by jmcanterafonseca** [comment]
@tobiasjacobs please check the proposed patch at https://github.com/telefonicaid/fiware-orion/pull/1524 

it is in good maturity now and will land shortly I think

**Comment by fgalan** [comment]
Taking into account that no feedbac has been provide since November 2015 in this issue, I understand that everybody is happy with the geo-location stuff in the current spec (or, in negative case, new issues would be opened about it). Thus, closing.
