### ISSUE TITLE
[QUESTION] Is It possible to update a metadata value in PATCH v2/entities/<id>?

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1786]
in PATCH `v2/entities/<id>` request.
## First question:

Is it possible to update a metadata value?
##### Update request

```
Content-Type: application/json
Fiware-Service: test_attribute_metadata_name_update
Fiware-ServicePath: /test
{"temperature": {"metadata": {"my_meta": {"value": "5678"}}}}
```
##### Update Response

```
http code: 400
date: Thu, 11 Feb 2016 10:42:06 GMT
connection: Keep-Alive
content-type: application/json
content-length: 88
{"error":"BadRequest","description":"no 'value' for ContextAttribute without keyValues"}
```
## Second question:

 Is it possible to append a new metadata in an existent attribute?

**Comment by fgalan** [comment]
As long as all the PUT/PATCH/POST operations on `/v2/entities/<id>` set each attribute "as a whole" (i.e. with value + type + metadata array) I understand that it is not possible.

**Comment by iariasleon** [comment]
OK, thanks

**Comment by jmcanterafonseca** [comment]
that's a bug. patch by definition

**Comment by fgalan** [comment]
> that's a bug. patch by definition should left existing info untouched. PUT is the operation to replace the whole content

The issue is more subtle...

Let's consider the general case in REST. For example, a three-level resource level: foo, bars and mu:

* Path to a foo resource: /foos/F
* Path to a bar resource (bar resources are sub-resources of foo): /foos/F1/bars/B1
* Path to a mu resource (nu resources are sub-resources of bar): /foos/F1/bars/B1/mus/M1

Let's consider the folowing operation:

```
PATCH /foos/F1/bars
{ B2: { M20: { ... }, M21: {...} }
```

That operation will change the content of bar resource B2 within F1, leaving untouched all the other bar resources in F1. I mean, if for example F1 has B1, then B1 is not changed. However, B2 is changed as a whole, i.e. M20 and M21 are not added to the existing mus of B2 previous to the PATCH operation. On the contrary, all the mus resources of B2 are replaced by M20 and M21.

If the purpose is to add M20 and M21 to B2, then the following operation will be used:

```
PATCH /foos/F1/bars/B2/mus
{ M20: { ... } , M21: { ... }
```

Applying this general principle to our case, PATCH /v2/entities/E1/attrs **cannot** be used to add new attributes to existing ones, as the patching is at attribute level. In order to add metadata to existing attributes PATCH /v2/entities/E1/attrs/A1/metadata operation should be used (an operation that is not part of the NGSIv1 API, so the API currently lacks of this capability).

**Comment by jmcanterafonseca** [comment]
as per RFC https://tools.ietf.org/html/rfc5789 

>
With PATCH, however, the enclosed entity contains a set
   of instructions describing how a resource currently residing on the
   origin server should be modified to produce a new version.  The PATCH
   method affects the resource identified by the Request-URI, and it
   also MAY have side effects on other resources; i.e., new resources
   may be created, or existing ones modified, by the application of a
   PATCH.
>

thus a patch over /v2/entities/attrs/myAttr may change a metadata without changing value, etc.

**Comment by fgalan** [comment]
It seems this issue is the same than #1788. I understand it is closeable.
