### ISSUE TITLE
patterns in entity types

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1853]
Like entity::id, _entity::type_ could have patterns.
Right now, without patterns for entity::type, a request gets either **one** entity or **all of them** (either for a specific _id_, or a patterned id).

Type patterns would be treated just like **id**, using either **type** or **typePattern** in the payload, and adding 'typePattern' as a URI param.

**Comment by fgalan** [comment]
Changes in NGSIv2 WIP .apib implemented in PR #2336

**Comment by fgalan** [comment]
Completed at NGSIv2 spec. Changing milestone to 1.3.0 (version in which this is going to be implemented at Orion).

**Comment by fgalan** [comment]
Some implementation notes follow:

Looking to the changes in the spec regarding this functionality (PR https://github.com/telefonicaid/fiware-orion/pull/2336) three operations are affected:

1. GET /v2/entities, where `typePattern` may appear as URL param.
2. POST /v2/op/query, where `typePattern` may appear in the payload
3. POST /v2/subscriptions or PATCH /v2/subscription/subId (most of the payload is the same), where `typePattern` may apper in the payload.

(The .spec also describes typePattern in the context of register context operation. However, given that the whole NGSI9 is not yet part of NGSIv2, we can discard that and it will not be considered part of the scope of the present issue).

Let's consider implication of the above three cases.

Regarding case 1 and 2, both are variants of query operations that at the end will end in the use of mongoQueryContext(), which uses a QueryContextRequest class as input argument. Thus, we need to extend that QueryContextRequest class (probably not QueryContextRequest class itself, but some of its contained clasess... I don't remember right now the details) to "map" the type pattern nature of a type. I mean, to implement a `isTypePattern` as "parallell" of `isPattern`.

*It important to note that typePattern is a functionality only in the NGSIv2 API. In other words, we are extending NGSIv1-biased classes to reuse mongoBackend, but not for exposing the functionality in the NGSIv1 API, i.e. no modifications to NGSIv1 parser.*

Moreover, internally the mongoBackend has to be modified to take into account that `isTypePattern` and adjust the query to MongoDB accordingly. This means changes in entitiesQuery() function, probably in the fillQueryEntity() which is called as first step.

Regarding case 3, it has two aspects: the basic create/update/retrieve subscription logic (3a) and the interpretation of the typePattern which is part of the subscription during an update context (in order to know if the update will trigger the notification associated to that subscription or not) (3b).

* (3a) Basically:
  * (3.a.1) We need to extend the csub database model to include a field for typePattern. Looking to https://fiware-orion.readthedocs.io/en/develop/admin/database_model/index.html#csubs-collection, probably a `isTypePattern` parallel to `isPattern` for ids will be the best approach.
  * (3.a.2) In addition, the CacheSubscription class (not sure if this is the name... I mean the class that represents a subscription ni the cache) need to be extended to include the typePattern nature of an entity (in an analogous way that the one used for id patterns)
* (3b) 
 * Considering cache usage, the function that "gathers" candidate subscription is addTriggeredSubscriptions_withCache(). Looking into it, probably is a matter of modifying subCacheMatch() execution flow in order to include the field mentioned in (3.a.2) as part of the matching process.
 * Considering no cache usage, the function that "gathers" candidate subscription is addTriggeredSubscriptions_noCache(). It seems that a JS function is used in this case to catch patterns id patterns, so it should be extended to cach also type patterns.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/2438 implements parts related with mongoBackend:

* the `isTypePattern` is taken into consideration in mongoQueryContext operations (items 1 and 2 in the above comment)
* the addTriggeredSubscriptions_noCache() function has been extended to consider the `isTypePattern` field (item 3.b.1).

What has not been done in #2438 is the persistence/retrieval operations for the `isTypePattern` field, i.e. the mongoBacken part for GET/POST/PATCH /v2/subscriptions ops (3.a.1).

**Comment by fgalan** [comment]
Finished by PR https://github.com/telefonicaid/fiware-orion/pull/2486

Ready for QA validation

**Comment by iariasleon** [comment]
this feature should be tested in:
  - GET /v2/entitites (URI param)
  - POST /v2/op/query (payload)
  - POST /v2/subscription (payload)
  - PATCH /v2/subscription (payload)
  
Now, it is only tested in  the [subscription notifications](https://github.com/telefonicaid/fiware-orion/blob/develop/test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_subject_entities.feature#L480) tests suite.

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/020_pep2cbv2_patternsinentitytypes.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
