### ISSUE TITLE
[BUG] in POST v2/subscriptions the "condition" field is not the same in DB

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1950]
in POST v2/subscriptions the "condition" field is not the same in DB, it is"conditions".

Suggestions:
  - the `expression` field in DB could be within the `conditions` field as the request.
  - the `conditions` field now is an array, couldn't it be a json object?
  - Is the`"format"` field useful? In v2, the XML format is not used.

#### Subcription request
```
POST http://localhost:1026/v2/subscriptions
Content-Type: application/json
Fiware-Service: test_casub_happy_path
Fiware-ServicePath: /test
 {
 	"description": "my first subscription",
 	"subject": {
 		"entities": [{
 			"idPattern": ".*",
 			"type": "room"
 		}],
 		"condition": {
 			"attributes": ["temperature_0", "temperature_1", "temperature_2"],
 			"expression": {
 				"q": "temperature>40"
 			}
 		},
 		"notification": {
 			"callback": "http://localhost:1234",
 			"throttling": 5,
 			"attributes": ["temperature_0", "temperature_1", "temperature_2"]
 		}
 	}
 }
```
#### Mongo Doc
```
{
	"reference": "http://localhost:1234",
	"throttling": 5 L,
	"expression": {
		"q": "temperature>40",
		"geometry": "",
		"georel": "",
		"coords": ""
	},
	"format": "JSON",
	"entities": [{
		"type": "room_0",
		"id": ".*",
		"isPattern": "true"
	}, {
		"type": "room_1",
		"id": ".*",
		"isPattern": "true"
	}],
	"expiration": 1459864800 L,
	"servicePath": "/test",
	"_id": ObjectId("56f2fecd0a2e2a8abc55a723"),
	"conditions": [{
		"type": "ONCHANGE",
		"value": ["temperature_0", "temperature_1", "temperature_2"]
	}],
	"attrs": ["temperature_0", "temperature_1", "temperature_2"]
}
```

**Comment by fgalan** [comment]
Different things to take into account regarding this issue:

* The API fields are in principle independent of the ones used at DB. In fact, API users don't need even to know about the DB model (or the DB itself! :), DB model information is only for Orion service administrators. Thus, it is ok to name `condition` in the API and `conditions` in the DB. Of course, if we would start from the scratch to design the CB we will use `condition` also in DB, but note that the DB model comes from NGSIv1 where `conditions` make fully sense and it is very HARD to change (changes in DB model involve migrating DBs in running Orion deployments). However, for this particular case, we have a tech debt issue https://github.com/telefonicaid/fiware-orion/issues/1851 about optimizing the conditions field in the DB and that would be a good moment to implement something like this. I have take not in that issue.

*  Regarding `conditions` (at DB) being an array, that is due to legacy reasons in pre-ONTIMINTERVAL times. This can be optimized, but not as a bug, but as a tech debt issue (the aforementioned #1851) 

* The format field is preserved to distinguish in the future between the different times of notifications formats in NGSIv2 (see https://github.com/telefonicaid/fiware-orion/issues/1875). Thus "JSON" will remain for legacy NGSIv1 format (the only one supported at current Orion 1.0.0), to be expaned in the future with "NGSIv2-NORMALIZED", "NGSIV2-KEYVALUES" and "NGSIV2-VALUES",

Side-note: you should prepare test cases for the 4 notifications formats: JSON, NGSIv2-NORMALIZED, NGSIV2-KEYVALUES and NGSIV2-VALUES.

**Comment by iariasleon** [comment]
LGTM
