### ISSUE TITLE
Get entity by id with default service path

### ISSUE THREAD

**Issue by DmitryPranchuk** [telefonicaid/fiware-orion#1957]
**Preconditions**
I have two entities with same type and ID in orion(different service paths - /aaa and /bbb for example). 
**Action**
I want to get one of my entity.
**Steps to reproduce**
1. I'm executing get request with ID and type (without service path header).
**Result**
Entity from service path /aaa or /bbb (maybe depends on which was created early)
**Expected result**
404 Not Found
**Orion version**
0.28.0-next (latest in docker hub at this moment)

**Comment by fgalan** [comment]
This is expected behaviour. Note that "no service path header" is interpreted as implicit `/#` in query operations, which means to use a scope consiting in root service + all their descendants.

From documentation at http://fiware-orion.readthedocs.org/en/0.28.0/user/service_path/:

> Fiware-ServicePath is an optional header. It is assumed that all the entities created without Fiware-ServicePath (or that don't include service path information in the database) belongs to a root scope "/" implicitely. All the queries without using Fiware-ServicePath are on "/#" implicitely. This behavior ensures backward compatibility to pre-0.14.0 versions.

and

> Scopes are hierarchical and hierarchical search can be done. In order to do that the '#' special keyword is used. Thus, a queryContext with pattern entity id “.*” of type “Tree” in /Madrid/Gardens/ParqueNorte/# will return all the trees in ParqueNorte, Parterre1 and Parterre2.

**Comment by DmitryPranchuk** [comment]
But then in my case it should return two entities (from /aaa and /bbb). But it returns only one.

**Comment by fgalan** [comment]
Sorry... I missunderstand your report.

Could you provide the exact operation you are using to query, please? There are several ways to query with Orion and I'd like to know exactly which ones are you using (as the bug could affect them but not others).

**Comment by DmitryPranchuk** [comment]
```
orionhost:1026/v1/contextEntities/entityId
```

There are two entities with ID "entityID" in orion. One in /aaa servicePath, and another in /bbb servicePath.

**Comment by fgalan** [comment]
Thanks for the feedback! Scheduling to milestone Orion 1.1.0 to have a look in deep.

**Comment by fgalan** [comment]
The `GET /v1/contextEntities/entityId` operation was designed to return just one entity. Thus, in the case of more than one matching entities, only one is returned. This is considered a "bad input" behaviour (as the client should do a query narrower enough to capture just one entity) and traced in the CB log:

```
Raising alarm BadInput 0.0.0.0: more than one context element found the this query - selecting the first one
```

Note that the following operations will return both entities (as they are designed to return many entities):

Example 1:

```
curl localhost:1026/v1/queryContext --header 'Content-Type: application/json' -d @- <<EOF
{
  "entities": [ 
    {
      "id": "E",
      "type": "T",
      "isPattern": "false"
    } 
  ] 
}
EOF
```

Example 2:

```
curl localhost:1026/v1/contextEntitites
```

As final comment, we are not very happy with the way in which `GET /v1/contexEntities/id` behaves with regards the case of many entities result (see https://github.com/telefonicaid/fiware-orion/issues/588). This has been fixed in the new operations set in NGSIv2. I recommend you to have a look to the [NGSIv2 specification](http://telefonicaid.github.io/fiware-orion/api/v2/) about new and more conveniente ways of doing queries for entities (including filtering funcitionality).

**Comment by fgalan** [comment]
At the end, not an actual bug/issue. Closing.
