### ISSUE TITLE
Notification status (like current notification timesSent)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-orion#1960]
I was wondering if in the same way that notification count is stored and increased it would be possible to store something about last notification status, like endpoint not exists, or connection refused, or something like that.
The insight is to know if notification is really working or not, and why.

**Comment by fgalan** [comment]
A very interesting feature... labeling with the "backlog" and "apiv2" labels. Thanks!

**Comment by fgalan** [comment]
_Functional specification:_

The following sub-fields will be added to `notification` field. They are only-read field, i.e. I cannot be touched on subscription creation/modification operations. In this sense, deal with it in the exact same way `timesSent` and `lastNotification` are dealt in the current implementation.

- `lastFailure`: the timestamp corresponding to the last failed notification. If the notification is ok, then this field is not included (that ensures backward compatibility).
- `timesFailed`: times count on how many times a notification was sent and failed, since last notification failure (i.e. if the subscriptions recovers, the timesFailed is reseted for the new fail period). If the notification is ok, then this field is not included (that ensures backward compatibility).

In addition, the `status` field would implement a new value:

- `fail`: the subscription is currently in failling status.

The .apib file needs to be modified accordingly to describe the new fields.

**Comment by fgalan** [comment]
lastFilure and timesFailed covered by PR https://github.com/telefonicaid/fiware-orion/pull/2638. The status: failed part is pending for a next PR.

**Comment by fgalan** [comment]
Finished in PR https://github.com/telefonicaid/fiware-orion/pull/2708

**Comment by fgalan** [comment]
(Moving to the QATestPending milesnote, now that the "1.6.0 development window" has passed)

**Comment by iariasleon** [comment]
covered in E2E in features/pepflows/023_pep2cbv2_notificationstatusaspartofsubscriptioninfo.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
