### ISSUE TITLE
/v2/entities/{entityId}/attrs resource for NGSIv2

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2028]
As per the latest discussions we need to have

GET /v2/entities/{entityId}/attrs and PUT /v2/entities/{entityId}/attrs as per 

http://fiware.github.io/context.Orion/api/v2/cookbook/ 

(section Context attributes / attribute collection)

**Comment by fgalan** [comment]
Realted SOF question: http://stackoverflow.com/questions/36476300/list-all-entities-resources-functionality-seems-to-be-failing-in-api-v2

**Comment by fgalan** [comment]
After put these new proposed operations in context with all the pre-existing ones it seems that we have duplicated operations. See https://docs.google.com/spreadsheets/d/1fe4Bicq2xHe82ZwIFeoPUirBnwMqLkOXyUk6UWRAozc/edit#gid=0:

* 20 and 20a are actually the same operation, but with different URL
* Same with 21 and 21a

**Comment by fgalan** [comment]
After discussion at skype with @jmcanterafonseca, it seems that 20 and 21 are redundant and should be removed.

**Comment by fgalan** [comment]
After disccusion, we also need to adjust the following URLs:

PATCH /v2/entities/{entityId} -> PATCH /v2/entities/{entityId}/attrs
POST /v2/entities/{entityId} -> POST /v2/entities/{entityId}/attrs

**Comment by fgalan** [comment]
(Adjust https://docs.google.com/spreadsheets/d/1f4m624nmO3jRjNalGE11lFLQixnfCENMV6dc54wUCCg/edit#gid=0 before closing this issue)

**Comment by fgalan** [comment]
Implelmented in PR #2068.

@iariasleon note that some operations will break in your tests after merging that PR. Maybe we can leave this issue opened until you fix them again (the fix is very easy: just to add "/attrs" to the URL of the affected operations). In addition, you should include some tests for the "GET /v2/entities/<id>/attrs" operation (maybe reusing the ones for "GET /v2/entities/<id>" and checking that with new operation id and type are omitted).

**Comment by iariasleon** [comment]
LGTM

Tested and changes in https://github.com/telefonicaid/fiware-orion/pull/2084
