### ISSUE TITLE
Docker image size has grown 130MB

### ISSUE THREAD

**Issue by dmabtrg** [telefonicaid/fiware-orion#2063]
Since version 0.28, the docker image is ~130 MB larger than previous images.  After inspecting the image, it seems that the directory `/opt/libmicrohttpd-0.9.48/` is not removed from the image in the cleaning step.  Is this directory necessary? I see that there are other libmicrohttpd files and directories removed, but not this one.

Thanks.

**Comment by fgalan** [comment]
Good point. That is probably is due to changed we did in libmicrohttpd linking some time ago... why missed to remove the new building artifacts. It should be fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2065 (now merged) so the next docker image built by Dockerhub https://hub.docker.com/u/fiware/ should be much lighter.

Could you check and close this issue as solved in that case, please?

Thanks for the feedback!

**Comment by dmabtrg** [comment]
Just checked and the new image is back to the size of the older images.

Closing as solved.
