### ISSUE TITLE
in Update requests /v2/entities/<id>/attrs if id has a #, returns a 405, but without payload in the response

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2075]
in Update requests `/v2/entities/<id>/attrs` if id has a # , returns a 405, but without payload in the response.

#### 1. PATCH  request
```
PATCH http://localhost:1026/v2/entities/house_#/attrs
Content-Type: application/json
Fiware-Service: test_update_entity_id
Fiware-ServicePath: /test
{"temperature_0": {"value": "80"}, "temperature_1": {"value": "80"}}
```

#### 2. PUT request
```
PUT http://localhost:1026/v2/entities/house_#/attrs
Content-Type: application/json
Fiware-Service: test_update_entity_id
Fiware-ServicePath: /test
 {"pressure": {"value": "80"}}
```

#### 3. POST request
```
POST http://localhost:1026/v2/entities/house_#/attrs
Content-Type: application/json
Fiware-Service: test_update_entity_id
Fiware-ServicePath: /test
 {"humidity": {"value": "80"}}
```

#### update response
```
http code: 405
date: Fri, 22 Apr 2016 13:45:46 GMT
fiware-correlator: 8456f84c-0890-11e6-a3c3-005056a20feb
connection: Keep-Alive
content-length: 0
allow: GET, DELETE
```

#### expected response
```
http code: 405
...
{"error": "methodNotAllowed", "description": "not defined yet"}
```

**Comment by kzangeli** [comment]
A few things to correct in the description of this issue.

* First, the URI path to use is `/v2/entities/house_#`, not `/v2/entities/house_#/attrs`.
[ /v2/entities/\<entity-id\> only accepts GET and DELETE methods ]

* Secondly, the '#' in entity-id has nothing to do with 405, the broker doesn't get to the point where the entity-id is checked (# would provoke a 'forbidden character'), as it is interrupted by 405 Method Not Allowed.
 
That said, it is true that the broker returns no payload on 405 errors - this was defined that way for NGSIv1 and it hasn't been fixed yet for v2. **That** is what this issue is about.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2318. Please @iariasleon have a look and close it if you find it solved.

**Comment by iariasleon** [comment]
LGTM
```
http code: 405 - Method Not Allowed
headers:
   content-length: 63
   fiware-correlator: f0e1599e-4e6d-11e6-9033-005056a20feb
   connection: Keep-Alive
   allow: GET, DELETE
   date: Wed, 20 Jul 2016 11:34:38 GMT
   content-type: application/json
payload: {"error":"MethodNotAllowed","description":"method not allowed"}
```
