### ISSUE TITLE
Subscribe to entities by filtering

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2085]
It would be nice to be able to subscribe to entities by filtering. 

Now it is possible to subscribe to entities by id, idPattern or type. It would nice to be able to subscribe by filtering, by means of a query expression

```json
"entities": [
  {
     "expression": {
       "q": "'name == Elizalde'"
     } 
  }
]
```
It will allow to subscribe to those entities matching the expression (it could include geospatial conditions as well).

**Comment by fgalan** [comment]
If I'm understanding correctly, I think this issue is already covered by the follwoing issues:

* q filters in subscriptions. Already implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1687.
* geo-subscriptions: pending (issue #1678)

In that case, the present issue should be closed (as it would be ducplicated):

**Comment by jmcanterafonseca** [comment]
oh you are right. I was thinking on a use case that is already solved by what we have. 

sorry for the noise
