### ISSUE TITLE
in GET v2/entities if are using regexp in "q" query param and some attribute value is Int type

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2226]
in GET v2/entities if are using regexp in "q" query param and some attribute value is Int type, all entitites are returned,  

With tihese three entities (payloads):

```
{"type": "VcLA", "id": "room1",  "temperature":{"type": "celsius", "value": 34}, "humidity":{"type": "absolute", "value": 567}}
```

```
{"type": "0Dov", "id": "room2",  "pressure":{"type": "bar", "metadata": {"very_hard": {"value": "high", "type": "alarm"}}, "value": 989}}
```

```
{"type": "1Pij", "id": "room3",  "speed":{"type": "kmh", "value": 80}}
```
#### GET request:

```
url: GET http://localhost:10026/v2/entities?q=humidity~=100&options=count
headers:
    Fiware-Service: qap1
    Fiware-ServicePath: /ssp1
```
#### GET response: (no entity complies the condition)

```
http code: 200 - OK
headers:
   content-length: 346
   fiware-total-count: 3
   fiware-correlator: cb986166-2805-11e6-9333-fa163e026cb4
   date: Wed, 01 Jun 2016 14:33:23 GMT  
   content-type: application/json
payload: [{"id":"room1","type":"VcLA","humidity":{"type":"absolute","value":567,"metadata":{}},"temperature":{"type":"celsius","value":34,"metadata":{}}},{"id":"room2","type":"0Dov","pressure":{"type":"bar","value":989,"metadata":{"very_hard":{"type":"alarm","value":"high"}}}},{"id":"room3","type":"1Pij","speed":{"type":"kmh","value":80,"metadata":{}}}]
```
#### Expected response

```
http code: 200 - OK
headers:
   content-length: 2
   fiware-total-count: 0
   fiware-correlator: cb986166-2805-11e6-9333-fa163e026cb4
   date: Wed, 01 Jun 2016 14:33:23 GMT  
   content-type: application/json
payload: []
```

**Comment by kzangeli** [comment]
I've looked into this a little.
The reason that all entites are returned is that room1:humidity is integer and thus ignored. The resulting mongo filter list is empty and nothing is filtered.
~= is only for strings, and that is documented, so, we could say this is the expected behavior of orion.

We could also return an error if **q=X~=** is used and no mongo filters are added.

Also, we could add ' AND attr must be a string ' to the mongo query and that way an empty vector would be the result of the query.

Three solutions, the last one might be the best. Actually, all of them are pretty good.

**Comment by kzangeli** [comment]
A simple and perhaps not even terminated functest for this issue is found in the branch **bug/2226_q_string_match**, in origin. The test file is `2226_q_string_match/q_string_match.test`

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2853. @iariasleon pls recheck

**Comment by iariasleon** [comment]
LGTM. See https://github.com/telefonicaid/fiware-orion/pull/2854
