### ISSUE TITLE
in PUT admin/log with FATAL and WARN levels the value changed is not the expected

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2419]
in PUT admin/log with FATAL and WARN levels the value changed is not the expected

**FATAL** is changed to **NONE**
**WARN** is changed to **ERROR**

#### PUT Request
```
 PUT http://localhost:1026/admin/log?level=FATAL
```

#### Response
```
http code: 200 - OK
headers:
   date: Tue, 02 Aug 2016 12:06:53 GMT
   fiware-correlator: 9a071a1e-58a9-11e6-b2f1-005056a20feb
   connection: Keep-Alive
   content-length: 0
payload:
```

#### GET Request
```
 GET http://localhost:1026/admin/log
```

#### Response
```
http code: 200 - OK
headers:
   date: Tue, 02 Aug 2016 12:06:53 GMT
   fiware-correlator: 9a11d972-58a9-11e6-88bd-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 16
payload: {"level":"NONE"}
```

Also, Always is logged this line (both at successful and unsuccessful cases):
```
time=2016-08-02T12:00:26.990Z | lvl=DEBUG | corr=b374a6d4-58a8-11e6-8008-005056a20feb | trans=1470139009-514-00000000004 | from=127.0.0.1 | srv=pending | subsrv=pending | comp=Orion | op=rest.cpp[212]:uriArgumentGet | msg=Received unrecognized URI parameter: 'level'

```

**Comment by iariasleon** [comment]
CB version used:
```
  "version" : "1.2.0-next",
  "git_hash" : "2952223adca30f1ff71f15dbc7e44c3c1fb1137f"
```

**Comment by iariasleon** [comment]
in CB version:
```
  "version" : "1.2.0-next",
  "git_hash" : "59c5c77580ad764684d2e650cc28d916dea41122",
```
Now:
* the `FATAL` level is returned as `FATAL`
* the `WARN` level is returned as `WARN`

But:
* the `NONE` level is returned as `FATAL`

#### PUT request
```
url: PUT http://localhost:1026/admin/log?level=NONE
```

#### GET request
```
url: GET http://localhost:1026/admin/log
```
#### GET response
```
http code: 200 - OK
headers:
   date: Tue, 23 Aug 2016 10:05:08 GMT
   fiware-correlator: 127b4694-6919-11e6-ab20-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 17
payload: {"level":"FATAL"}

```

**Comment by kzangeli** [comment]
The problem here is that FATAL doesn't exist in the broker.

    The broker never dies ... :-)

FATAL is converted to NONE internally and then converted back to FATAL in the GET operation.
Actually, the entire logLevel is a bitmask in the broker, with possibility to turn on only DEBUG and ERROR, skipping INFO and WARN that comes in between ...

However, the broker should behave as decided for all components and we might have to do something about this to make it right.
Change NONE to 'unfiltered' (which is really DEBUG, as that is the lowest possible level)  ?
But also, remembering NONE to be able to return it in a GET op.
Or, simply modify the documentation.

The usage of the contextBroker gives this description for logLevel:

    [option '-logLevel' <initial log level (NONE, ERROR, WARN, INFO, DEBUG)>]

There is no FATAL there.

The documentation includes both NONE and FATAL ...

**Comment by iariasleon** [comment]
Specification: https://fiware-orion.readthedocs.io/en/develop/admin/management_api/index.html#log-and-trace-levels

**Comment by iariasleon** [comment]
And in log is stored as `NONE` level
```
time=2016-08-23T10:58:44.816Z | lvl=INFO | corr=8f768f94-6920-11e6-86cf-005056a20feb | trans=1471949924-150-00000000002 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=logMsg.h[1808]:lmTransactionStart | msg=Starting transaction from 10.95.146.168:50586/admin/log
time=2016-08-23T10:58:44.817Z | lvl=DEBUG | corr=8f768f94-6920-11e6-86cf-005056a20feb | trans=1471949924-150-00000000002 | from=10.95.146.168 | srv=pending | subsrv=pending | comp=Orion | op=rest.cpp[226]:uriArgumentGet | msg=URI parameter:   level: NONE

```

**Comment by fgalan** [comment]
> The problem here is that FATAL doesn't exist in the broker. 

Not exactly... CB is able to produce messages in this level:

```
time=2016-08-26T10:15:21.548Z | lvl=FATAL | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[1535]:restStart | msg=Fatal Error (error starting REST interface)
```

However, CLI is correct not mentioning FATAL, which is a sub-class of ERROR. From https://fiware-orion.readthedocs.io/en/develop/admin/logs/index.html:

```
A subclass of ERROR is FATAL, which designates very severe error events that will presumably lead the application to abort. The process can no longer work.
```

**Comment by fgalan** [comment]
From IoTP requirements:

> The value of the "level" parameter is interpreted in a case insensitive way and the valid values are:
>
> FATAL, ERROR, WARNING, INFO, DEBUG

Thus, FATAL should be supported in this admin API. NONE is not required by IoTP, but given that for CB is a valid log level, we also should support and the bug detected by @iariasleon is meaningfull.

**Comment by kzangeli** [comment]
FATAL is supported as value in /admin/log?level=FATAL.

The only problem here is that FATAL internally in the broker is NONE, eitherthe logLevel was set to NONE or FATAL. These two are identical and the value for it is NONE.

So, when setting the logLevel (via REST) to FATAL or NONE, and later asking for it (GET /admin/logLevel) you get the same string.

The fix for this issue was that I changed that string from NONE to FATAL.

If we want the broker to respònd with NONE when NONE was set and FATAL when FATAL was set, then the broker will need to store that difference in a variable.

The fix is easy.
Is this what we want?

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/2477 is supposed to fix the last problem described by @iariasleon . Please, could you re-check?

**Comment by iariasleon** [comment]
LGTM 
```
http code: 200 - OK
headers:
   Connection: Keep-Alive
   Content-Length: 16
   Content-Type: application/json
   Fiware-Correlator: f16469fe-6de6-11e6-a60c-005056a20feb
   Date: Mon, 29 Aug 2016 12:48:54 GMT
payload: {"level":"NONE"}
```
