### ISSUE TITLE
crash with 1.3.0 version, if the BD is not migrated

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2441]
Crash with 1.3.0 version, if the BD is not migrated. When try to apply the subscriptions cache without the migrated. See [upgrading to 1.3.0](https://fiware-orion.readthedocs.io/en/develop/admin/upgrading_crossing_1-3-0/index.html).

```
time=2016-07-14T12:38:13.151Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | from=N/A | function=mongoSubCacheItemInsert | comp=Orion | msg=mongoSubCache.cpp[85]: allocated CachedSubscription at 0x1c2ab80
```

Returning only by console (no log):

```
terminate called after throwing an instance of 'mongo::MsgAssertionException'
  what():  wrong type for field ( 0 ) 3 != 2
```

Note: but if we use `-noCache` parameter, the CB is started correctly.

**Comment by fgalan** [comment]
It is assumed that the DB provided to CB on startup is not malformed, otherwise the CB is not expected to work properly or even it could crash (as in this case). From a post-1.2.0 CB any pre-1.2.0 DB is a malformed DB, so this is not actually a bug (removing bug and P8 labels). In addition, it doesn't work the effort to fix this particular crash, as it will be soon become obsolete (as now any similar problem with post-0.14.1 CB running any pre-0.14.1 DB is completely obsolete, as 0.14.1 is an ancient version).

However, some actions could be done regarding this.

1. Open an backlog issue about CB being able to detect malformed DBs in general an refuse to start or log the problem in an ordered manner.
2. Include a warning in the documentation about the DB provided to CB on startup is not malformed and that case of malformed DB are the not migrated DB used with newer versions of CB.

**Comment by fgalan** [comment]
This is a corner case for a version (1.3.0) that nowadays is pretty old. Closing.
