### ISSUE TITLE
Subscription endpoint called on update subscription

### ISSUE THREAD

**Issue by richturner** [telefonicaid/fiware-orion#2447]
I know that the subscription endpoint gets called when the subscription is first created; but it also seems to get called when the subscription is updated (in my case I am only updating the expiry). I don't think this should happen as the refreshing of the subscription expiry time is an implementation detail, the entities have not been modified in any way.

Is this anyway related to #2216

**Comment by fgalan** [comment]
That's correct, it is expected behaviour. However, in the same ways there are plans to make initial notification configurable at subscritpion creation time (see https://github.com/telefonicaid/fiware-orion/issues/920) the same solution could be applied for subscriptions updates.

In fact, in same sense, this issue could be seen as an "spin off" of #920, to be fixed at the sime time when the time comes.

Thanks for the feedback!

**Comment by fgalan** [comment]
Initial notification functionality has been deprecated in Orion 3.1.0 (to be release soon). Thus, taking into account the rules at https://fiware-orion.readthedocs.io/en/master/deprecated/index.html

> Bugs or issues related with deprecated features and not affecting any other feature are not addressed (they are closed in github.com as soon as they are spotted).

This issue is being closed.
