### ISSUE TITLE
Default attribute types: Denote precisely array attributes

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2449]
We need to be more explicit in order to distinguish between Arrays and Object Maps. I propose to use

type: `StructuredValue` for Object Maps as currently it is.
type: `Array` for attributes which are ordered collections of values. (Unfortunately there is nothing proposed yet by schema.org).

**Comment by fgalan** [comment]
This is related with #2223. The same comment there, applies here:

Maybe "StructuredValue" should be also used for arrays. Taking into account "StructureValue" definition:

> Structured values are used when the value of a property has a more complex structure than simply being a textual value or a reference to another thing.

array can be considered a case of "a more complex structure than simply being a textual value or a reference to another thing".

(Note that in Orion terms, we already -since time ago- use to refer to both (objects & arrays) as "compund values" or "structures values")

**Comment by jmcanterafonseca** [comment]
current plan is to leave this issue open and to get in touch with the
schema.org community to investigate why Array has not been used by
schema.org

2016-08-26 11:53 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
At the end, schema.org was contacted and we will keep using StructuredValue. Closing.
