### ISSUE TITLE
previousValue is not included in notifications (and it should) when only attribute type changes

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2588]
For subscriptions configured to include previousValue in notifications, this metadata (previousValue) is not included when only the attribute type changes. In other words, the event of changing type triggers the notification, but the notification doesn't include the previousValue corresponding to the attribute before changing type.

Example: the attribute is as follows

> type: T
> value: A

Then an update is sent with the following:

> type: T1 (it changes)
> value: A (it doesn't change)

This triggers a notification, that incluces A-T1. However, the previousValue with A-T is not included.

**Comment by fgalan** [comment]
Trying to reproduce, without sucess. Thus, the bug was incorrecntly detected or solved in some way since it was detected and now. A .test covering the case has been added in PR https://github.com/telefonicaid/fiware-orion/pull/2651.

Milestone has been assigned to 1.6 (the development cycle in which we have analyzed this and create the .test) although it could have been solved in a previous version.
