### ISSUE TITLE
[Number precision] JSON timestamp wrong on FIWARE Orion Context Broker global instance

### ISSUE THREAD

**Issue by y-luis** [telefonicaid/fiware-orion#2603]
Hi,

I am sending a POST request to http://orion.lab.fiware.org:1026/v2/entities/85/attrs?type=UrbansenseLocation in order to update _atime_ and _bundle_ attributes:

```
{
"atime":{
    "type":"Number",
    "value":1476370651},
"bundle":{
    "type":"Number",
    "value":1}
}
```

and a GET request to the same entity receives the following response:

```
{
"id": "85",
"type": "UrbansenseLocation",
"atime": {
    "type": "Number",
    "value": 1476370000,
    "metadata": {}
},
"bundle": {
    "type": "Number",
    "value": 1,
    "metadata": {}
},
//some other attributes
}
```

Please, note the mismatch on the value field of the _atime_ attribute!!! Why is such thing happening?

Thanks.

**Comment by fgalan** [comment]
(Also posted at SOF: http://stackoverflow.com/questions/40025243/json-timestamp-wrong-on-fiware-orion-context-broker-global-instance)

**Comment by fgalan** [comment]
Looking into the database:

```
> db.entities.find({"_id.id": "85", "_id.type": "UrbansenseLocation"}).pretty()
{
...
        "attrs" : {
                ...
                "atime" : {
                        "value" : 1476380652,
                        "type" : "Number",
                        ...
                },
...
}
```

It seems that the attribute value is correctly stored in the DB (so the parsing stage is not lossing precission). However, it seems that the number gets rounded from 1476380652 to 1476380000 in the rendering stage.

The relative rounding error is not too much (around ~4.4162e-07) but we should have a look to this into the code to make it more precise.

Thanks for the report!

**Comment by fgalan** [comment]
This is probably the function that needs to be adjusted to fix this problem (in string.cpp):

```
/* ****************************************************************************
*
* toString
*
* Specialized version of the template for the double type
*/
template <> std::string toString(double f)
{
  std::ostringstream ss;

  unsigned int digits = decimalDigits(f);
  if (digits > 0)
  {
    ss << std::fixed << std::setprecision(digits);
  }

  ss << f;

  return ss.str();
}
```

Playing with the stream modifier we could get more precission. However, adjusting this function to solve this problem could unadjust another rendering cases for number.

This issue is another "facet" os this one: https://github.com/telefonicaid/fiware-orion/issues/2425. Maybe both should be solved together.

**Comment by fgalan** [comment]
> The relative rounding error is not too much (around ~4.4162e-07) but we should have a look to this into the code to make it more precise.

However, considering them as timestamps:

- 1476380652 ->13 de octubre de 2016 19:44:12 GMT+2:00 DST
- 1476380000 -> 13 de octubre de 2016 19:33:20 GMT+2:00 DST

Around 11 min offset.

However, using `DateTime` for this attribute could provide a right render.

**Comment by fgalan** [comment]
Looking into this, it seems it is that the current rendering strategy is able to print integeres correctly. For instance, if we hack this way:

```
template <> std::string toString(double f)
{
  std::ostringstream ss;

  /*unsigned int digits = decimalDigits(f);
  if (digits > 0)
  {
    ss << std::fixed << std::setprecision(digits);
  }*/

  long long ff = 1528447077;

  //ss << f;
  ss << ff;

  return ss.str();
}
```

and we have at MongoDB:

```
{ "_id" : { "id" : "E", "type" : "Thing", "servicePath" : "/a" }, "attrNames" : [ "turn" ], "attrs" : { "turn" : { "type" : "string", "creDate" : 1528747352, "modDate" : 1528747352, "value" : 1528447077, "mdNames" : [ ] } }, "creDate" : 1528747352, "modDate" : 1528747352, "lastCorrelator" : "60916daa-6db2-11e8-9e33-000c29173617" }
```

then we get in the API the number correctly:

```
GET /v2/entities
[{"id":"E","type":"Thing","turn":{"type":"string","value":1528447077,"metadata":{}}}]
```

I think the root of this problem is that we use `double numberValue` in ContextAttribute class and we lost in the cast when the original number (in DB) is intenger. It is a bit funny, because the "lower part" of our code (the one that grab the data from DB) is prepared to disntiguish between integers and float, but, at the end we are not taken advantage of it. For instance, in ContextelementResponse.cpp:

```
...
      case NumberDouble:
        ca.numberValue = getNumberFieldF(attr, ENT_ATTRS_VALUE);
        caP = new ContextAttribute(ca.name, ca.type, ca.numberValue);
        break;

      case NumberInt:
        ca.numberValue = (double) getIntFieldF(attr, ENT_ATTRS_VALUE);
        caP = new ContextAttribute(ca.name, ca.type, ca.numberValue);
        break;
...
```

The solution would be to include `int numberIntegerValue` (or a larger one, such `long`, `long long`, etc.) in ContextAtrribute class, then the above code could be rewritteng this way:

```
...
      case NumberDouble:
        ca.numberValue = getNumberFieldF(attr, ENT_ATTRS_VALUE);
        caP = new ContextAttribute(ca.name, ca.type, ca.numberValue);
        break;

      case NumberInt:
        ca.numberIntegerValue = getIntFieldF(attr, ENT_ATTRS_VALUE);
        caP = new ContextAttribute(ca.name, ca.type, ca.numberValue);
        break;
...
```

and also add: 

* A new element to `ValueType` (eg: `ValueTypeIntegerNumber`)
* A  new `template <> std::string toString(int/long/etc n)` function

These would be the main change but other ones would be probably needed. As far as I have checked, `numberValue` is used in 48 places in the code, that would need adjusted.

**Comment by fgalan** [comment]
Related with this, I have found something a bit surprising. In our NGSIv2 parsing logic (parseContextAttribute.cpp) we have:

```
      else if (type == "Number")
      {
        caP->numberValue  = iter->value.GetDouble();
        caP->valueType    = orion::ValueTypeNumber;
      }
```

So a casting is also done here (internally, by the GetDouble() function)... with the diference that in this place it works and ends with a true integer in the DB. Looking into the details of GetDouble:

```
    double GetDouble() const {
        RAPIDJSON_ASSERT(IsNumber());
        if ((flags_ & kDoubleFlag) != 0)                return data_.n.d;   // exact type, no conversion.
        if ((flags_ & kIntFlag) != 0)                   return data_.n.i.i; // int -> double
        if ((flags_ & kUintFlag) != 0)                  return data_.n.u.u; // unsigned -> double
        if ((flags_ & kInt64Flag) != 0)                 return (double)data_.n.i64; // int64_t -> double (may lose precision)
        RAPIDJSON_ASSERT((flags_ & kUint64Flag) != 0);  return (double)data_.n.u64; // uint64_t -> double (may lose precision)
    }
```

Maybe the key is that the `data_.n` object has all the possible variants of the number (`d` for double, `i.i.` for integer, etc.)?

If we could do a similar "safe casting" in our code maybe we could limit the impact of the modifications to `case NumberInt` shown in  my previous comment... but maybe it is not possible.

**Comment by fgalan** [comment]
Quick fix in PR https://github.com/telefonicaid/fiware-orion/pull/3229.

**Comment by fgalan** [comment]
I'd say that PR https://github.com/telefonicaid/fiware-orion/pull/3285 provides a definitive solution to this issue, so it can be closed. @kzangeli what do you think?
