### ISSUE TITLE
API specification with swagger 

### ISSUE THREAD

**Issue by glikson** [telefonicaid/fiware-orion#2766]
It could be very useful to have a Swagger specification of the API. It could make it easier to integrate Orion/NGSI with other systems/applications. Are there plans to develop such specification?

**Comment by fgalan** [comment]
According to FIWARE Development Guide (https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Developer_Guidelines#Summary_of_MUST_Guidelines) is is mandatory to use Apiary as API framework instead of Swagger:

> Should you want to benefit from FIWARE automatic documentation generation systems you MUST use markdown for documentation and Apiary Blue Print for API specification. 

(In fact, I think that Swagger was considered as alternative to Apiary when the Guide was defined, and Apiary was chosen as the best option)

I guess that it could be possible to keep a parallel Swagger specification to Apiary, but it would involve a significative effort. Thus, there isn't any plan at the current moment to develop an Swagger specification. However, we will be very happy to see external contributions in this line :)
