### ISSUE TITLE
Exclude paused subscriptions from csub cache

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2784]
csubs cache was designed to speed up csub search upon update entitie operations. 
So paused subscription should be removed from csub cache. This has two advantages:

* Faster searches (the main one)
* Reduce cache memory footprint (secondary one, but also important, as https://github.com/telefonicaid/fiware-orion/issues/2780 shows)

When a subscription is set to **Pause** state, it is removed from the cache, and when put in **Active** state again it is reinserted in the cache.

**Comment by fgalan** [comment]
Related issue #2788

**Comment by Anjali-NEC** [comment]
Hi @fgalan sir,

I would like to work on this issue, As per my understanding we need to remove paused subscription from csub cache and when paused subscription put in Active state again it is reinserted in the cache. One thing I want to clear, is paused subscription are inactive subscriptions or expired subscriptions? Please confirm.

Please ,confirm my understanding and Let me know this issue is still valid or not.

**Comment by fgalan** [comment]
This issue was opened time ago (year 2016). Since them, experience has shown that paused subscription are rarely used (less than 1% of subscriptions) so implementing pause subscription exclusion from cscub probably doesn't worth the effort (the cache is a difficult part of the code).

I'd close the issue. Thanks for spotting it!
