### ISSUE TITLE
[bug] null values are incorrectly used when ordering entities by attribute value

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2802]
If an attribute has a value of 'null' and entities are ordered by such attribute, the CB uses incorrectly the `null' value as the lowest one and returns and array of entities with those which attribute value is 'null' first. 

http://130.206.118.244:1027/v2/entities?type=WeatherObserved&q=dateObserved>=2017-01-09&orderBy=temperature&attrs=temperature,address&options=keyValues 

to reproduce a token is needed as per https://docs.google.com/document/d/1lHP7XS-7TNzsxLa0bNFb-96JnJXh0ecIHS3-H0qMREg/edit#

There should be an option to put null values last (or do it by default) or allow to filter by attribute value <> null. See next issue.

**Comment by fgalan** [comment]
> See next issue?

Does it refer to https://github.com/telefonicaid/fiware-orion/issues/2803 ?

**Comment by jmcanterafonseca** [comment]
yup ;)

2017-01-09 16:43 GMT+01:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
This is not actually a bug. Whenever you are comparing things that are not "naturally" comparable (e.g. a number is not comparable to a boolean or a string, for example) you need to define a convention. In this case, the convention is the one used by MongoDB due to implementation reasong that is not worse (or better) than any other (https://docs.mongodb.com/manual/reference/method/cursor.sort/):

1. MinKey (internal type)
2. Null
3. Numbers (ints, longs, doubles, decimals)
4. Symbol, String
5. Object
6. Array
7. BinData
8 ObjectId
9. Boolean
10. Date
11. Timestamp
12. Regular Expression
13. MaxKey (internal type)

However, NGSIv2 implementation notes document should explain this. This issue will remain open in order to fix documentation.

**Comment by fgalan** [comment]
Documentation added with PR https://github.com/telefonicaid/fiware-orion/pull/2857. Closing.
