### ISSUE TITLE
Quote not working for complex filters (and maybe in other cases...)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2805]
I have an strong feeling (need to be checked) that the following from NGSIv2 spec (only in WIP version at this moment) http://fiware.github.io/specifications/ngsiv2/latest:

> In case some of the tokens include `.`, you can use single quote (`'`) as separator. For example, the following attribute path `'a.b'.w.'x.y'` is composed by three tokens: the first token is `a.b`, the second token is `w` and the third token is `x.y`.

is not actually working.

**Comment by kzangeli** [comment]
grep for orionCurl and the `'` char doesn't help at all, as most URLs with URI params use the quote to avoid sending the command into background due to the '&' char:
```
orionCurl --url '/v2/entities?q=S==1&options=keyValues'
```

However, I did a manual search and found very little:

```
1595_query_with_q_and_string_values/query_with_q_and_string_values.test:orionCurl --url "/v2/entities?q=A1=='10'"
1595_query_with_q_and_string_values/query_with_q_and_string_values.test:orionCurl --url "/v2/entities?q=A1!='10'"
1595_query_with_q_and_string_values/query_with_q_and_string_values.test:orionCurl --url "/v2/entities?q=A1=='10'x"
1595_query_with_q_and_string_values/query_with_q_and_string_values.test:orionCurl --url "/v2/entities?q=A1=='10'x'"
1129_strings_in_q_uri_param/strings_in_q_uri_param.test:orionCurl --url "/v2/entities?q=S:'123'&options=keyValues"
```

So, the quote is only used in functests to "make ints be treated as strings".

It seems this feature is completely untested, perhaps not even implemented ...
No worries about duplicating functests :-)

**Comment by fgalan** [comment]
Partly implemented in PR https://github.com/telefonicaid/fiware-orion/pull/2808

**Comment by fgalan** [comment]
Finished (with a comprehesive regresion .test) in PR https://github.com/telefonicaid/fiware-orion/pull/2809
