### ISSUE TITLE
Check functionality of quotes in string filters

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2807]
We should do a review of use cases with quote (') described in the "Simple Query Language" section and check that all of them are correctly implemented.

[ But not create new test cases for already covered cases ]

**Comment by fgalan** [comment]
This issue is an spin-off of https://github.com/telefonicaid/fiware-orion/issues/2805.

We have the following cases

* Number as string
* Bool as string
* Null as string

According to https://github.com/telefonicaid/fiware-orion/issues/2805#issuecomment-271856667, the fist one is already covered by 1595_query_with_q_and_string_values/query_with_q_and_string_values.test so this issue should focus in second and third case.

**Comment by fgalan** [comment]
.test to cover all cases in PR https://github.com/telefonicaid/fiware-orion/pull/2810
