### ISSUE TITLE
The function parseEntity() should be looked over

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2883]
The function `parseEntity()` (parsing of JSON NGSIv2) implements "error for **Entity::id** set but as empty string" in one way and "error for **Entity::type** set but as empty string" in another way.

Entity::type has the better implementation and the treatment of the error for Entity::id should be done the same way.

Actually, the function would be easier to understand if rewritten a little.

**Comment by Anjali-NEC** [comment]
Hi @kzangeli @fgalan Sir,

I would like to work on this issue. As per my understanding we need to rewrite the code of Entity::id in case of "empty entity id error" same as written for Entity::type for empty type case in https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/jsonParseV2/parseEntity.cpp#L200

**Comment by fgalan** [comment]
I have looked for "set but as empty string" string on the code and I have not found any occurrence. This makes me think that maybe this issue is old and maybe the parsing logic was refactored after issue creation and now the code it's fine. Note the code at https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/jsonParseV2/parseEntity.cpp#L261 is pretty similar to the one your are citing.

However, it would be great if you could have a look. If you think the code in parseEntity.cpp as it is now it's fine, then tell us and this issue would be closed without any further action. On the other hand, if you think there is some room for improvement, then do it in a pull request so we can have a look and provide feedback.

Thanks!

**Comment by Anjali-NEC** [comment]
@fgalan Sir, Yes you are right this issue was fixed. But I think some improvement is required in the code. like the code written for the checking of empty id in line 259 to 270 should be move to the line number 164 where checking of id was done just like similar to the type. It would be easier to understand. 

I have raised PR for this, Please have a look, if its is ok then please merge into master.
