### ISSUE TITLE
Align /version with Fiware scheme

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2970]
We need to create a new resource in all RESTful interfaces of GEris/GEis and also incubated project following the description provided in the following document:

https://docs.google.com/document/d/1hJgawz4ibu1OBA_OlqVfZY7fzIHQ0c4vd5b-T7r2nHM/edit

**Comment by jmcanterafonseca** [comment]
Assigned to Burak Karaboga (ATOS)

**Comment by fgalan** [comment]
Thinking on how `GET /version` works right now, if the client processes the response JSON-wise, the modification which this issue involves shouldn't break. But if the client processes the response text-wise (e.g. "take the four line, then take from 25-th character on") it will break.

Regular operations in the API (e.g. NGSIv2 ops) shouldn't be processed text-wise and in that case I wouldn't have this concern. But the version operation is special, it is used sometimes by clients which are not full fledged REST clients (e.g. simple probe in monitoring systems which no JSON processing library or capabilities) which adopt a text-wise approach.

Thus, I wonder why changing it and take an unnecessary backward compatibility risk. Which *real problem* is https://docs.google.com/document/d/1hJgawz4ibu1OBA_OlqVfZY7fzIHQ0c4vd5b-T7r2nHM/edit solving?

**Comment by jmcanterafonseca** [comment]
@flopezag proposed that so he can clarify. 

In order to solve the issue you mentioned I would suggest we add any new or extra field at the end of the payload and keep the first n positions of the current payload untouched

**Comment by flopezag** [comment]
Dear @fgalan, it is something that what proposed by the FIWARE TSC in order to identify clearly which is the current version of the FIWARE GEri/GEi that it is running in order to proceed accordingly with the corresponding operations (e.g. testing procedures and monitoring).

The description was taking from the current publication of Orion plus some extra information, mainly in order that Orion does not need to change anything on it and approved in the TSC.

In case that you see any specific things that is not following the current Orion solution let us know in order to analyse it or if you have identified any problem on some of the content on it let us know in order to evaluate the problem and put together and workaround to resolve it.

**Comment by fgalan** [comment]
@flopezag the specific problem is what I mention in my first comment:

> If the client processes the response JSON-wise, the modification which this issue involves shouldn't break. **But if the client processes the response text-wise (e.g. "take the four line, then take from 25-th character on") it will break.**

You may argue that if the client process a JSON response text-wise is a problem at the client. I agree with that in the 99% of the cases, but this operation is somehow special, as I also mention in my previous comment:

> Regular operations in the API (e.g. NGSIv2 ops) shouldn't be processed text-wise and in that case I wouldn't have this concern. But the version operation is special, it is used sometimes by clients which are not full fledged REST clients (e.g. simple probe in monitoring systems which no JSON processing library or capabilities) which adopt a text-wise approach.

However, I think that @jmcanterafonseca 's commen points in the right direction

> In order to solve the issue you mentioned I would suggest we add any new or extra field at the end of the payload and keep the first n positions of the current payload untouched

Let me think a bit on this so I can come with an specific proposal on what to change and how.

**Comment by flopezag** [comment]
Probably, you are right because I do not see the difference with the current status or in which key-value pair you see a problem.

**Comment by fgalan** [comment]
Currently (1.8.0) Orion implements `GET /version` like this:

```
{
"orion" : {
  "version" : "1.8.0-next",
  "uptime" : "0 d, 0 h, 0 m, 4 s",
  "git_hash" : "10cbb3898840f49e93bf804e22e627e3a60edbad",
  "compile_time" : "Tue Sep 12 08:58:55 CEST 2017",
  "compiled_by" : "fermin",
  "compiled_in" : "neodeb"
}
}
```

In order to minimize the risk in extinging text-wise clients of this operation, and aligned with the suggestion by @jmcanterafonseca , let's add the new fields *at the end*, i.e.:

```
{
"orion" : {
  "version" : "1.8.0-next",
  "uptime" : "0 d, 0 h, 0 m, 4 s",
  "git_hash" : "10cbb3898840f49e93bf804e22e627e3a60edbad",
  "compile_time" : "Tue Sep 12 08:58:55 CEST 2017",
  "compiled_by" : "fermin",
  "compiled_in" : "neodeb",
  "release_date": "...",
  "doc": "..."
}
}
```
With regard to the new fields:

* To be coherent, "release_date" will use the same format that existing "compile_time"
* The URL to use in "doc" will be the one corresponding to the Orion manual, i.e. `https://fiware-orion.readthedocs.org/en/master/` in the master branch and `http://fiware-orion.readthedocs.io/en/x.y.z` in release/x.y.z branches
  *  In a first version of the implementation of this issue (i.e. in a first PR), let's hardwire `https://fiware-orion.readthedocs.org/en/master/`. The adjustement in release.sh to change URL with the right version number upon releasing will be done as a future improvement.

With regards to https://docs.google.com/document/d/1hJgawz4ibu1OBA_OlqVfZY7fzIHQ0c4vd5b-T7r2nHM/edit the following modifications would be needed:

* *"Release_date: I shows the date of the release in YYYY-MM-DD format"* should be changes by *"Release_date: It shows the date of the release. The recomended format is YYYY-MM-DD format but other format are also allowed*.
* *Doc: link to the API documentation in the gh-pages (.github.io/) inside the fiware organization in GitHub* should be changed by *"Doc: link to the GEri documentation, either in the gh-pages (.github.io/) inside the fiware organization in GitHub or ReadTheDocs manual"*.

With regard to .test, this issue doesn't involve new .test files, but modification on existing ones. Follow the following procedure:

* Search for all .test using the `GET /version` operation (hint: grep for `/version`)
* Use `--noPayloadCheck` in the orionCurl corresponding to `GET /version` steps (as now the order of the field has become imporant)
* Adjust the REGEXPECT of these .test accordingly (reordering fields in current REGEXPECT and adding the new ones)

**Comment by fgalan** [comment]
Implemented (except the part of dynamically chaning `doc` to adjust the version name) in PR https://github.com/telefonicaid/fiware-orion/pull/2971

**Comment by fgalan** [comment]
Reonpening, as the part to dynamically change the doc string upon releasing is yete pending. Assigned to @fgalan to complete that minor part.

**Comment by fgalan** [comment]
release.sh adjust donde in PR https://github.com/telefonicaid/fiware-orion/pull/2992

Once merged, we cannot test the change in release.sh was ok until we release next version (1.9.0). Thus, the present issue should remain open until that.

**Comment by fgalan** [comment]
> Once merged, we cannot test the change in release.sh was ok until we release next version (1.9.0). Thus, the present issue should remain open until that.

We have just released 1.9.0 and I'm afraid it has not working. It seems src/lib/common/defaultValues.h file is not included in the git add step in release.sh.

Moving to milestone 1.10.0, to attemp to fix for the next release.

**Comment by fgalan** [comment]
New attemp to fix in PR https://github.com/telefonicaid/fiware-orion/pull/3021

**Comment by fgalan** [comment]
release.sh was used to generate 1.10.0 and it is ok. Closing.
