### ISSUE TITLE
Allow creation of transient entities

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#3000]
It will nice to have a functionality that allows to create transient entities. 

At creation time a new attribute `dateExpires` will state the date and time at which the entity will be expired. Expired entities will automatically removed by the system. 

`dateExpires` is an attribute that could be updated but probably not shown during a regular API query call as it happens with `dateCreated` and `dateModified`.

**Comment by fgalan** [comment]
_Implementation notes_

MongoDB has a nice feature named TTL that can be used: https://docs.mongodb.com/manual/tutorial/expire-data/

Thus, as far as I understand, this issue will be implemented in the following way:

* Defining a new field for expiration in the entities collection. Not sure if we should use `dateExpiration` (aligning with the API) or `expiration` (aligning with similar fileds in csubs and registrations collecitions)
* Create a TTL index on that field. That index will be managed by Orion, similarly to the current index in `location.coords`, e.g. creating it at boot time. Look for alll places in which `location.coord` is created/destroyed and implement a similar operation.
* `dateExpires` will be a virtual attribute, omitted by default but shown with `attrs` (same behaviour as e.g. `dateModified`.
* All the transition will be possible (and the associated .test has to check them all):
  * Create an entity from scratch with `dateExpires` attribute
  * Add `dateExpired` attribute to a regular entity, becoming it expirable
  * Removing `dateExpired` attribute to an expirable entity, becoming it regular
* Note that different to current `expiration` in csubs and registration, the MongoDB feature requires the new field to be a Date object at BSON level. This make the implementation less direct, but it doesn't seem to be very difficult anyway.

Caveat: `dateExpires` could be in use in some current DB as at the present moment it doesn't have any special semantic. So, collission may occcur (although it is not very probable). We have to think about what to do in this situation...

**Comment by jmcanterafonseca** [comment]
@arigliano would you like to work on this?

**Comment by arigliano** [comment]
Hi all, I would like to start working on this issue. As far as i see, the described logic should be implemented in the **processContextElement()** function. As regards **processRegisterContext**, however, since it already manages the duration, which has a different meaning for the context registration, no change should be made. In any case, I'm looking for the part regarding the creation of location.coors for implementation hints.

**Comment by fgalan** [comment]
As far as I remember (not sure of all the subtle deatails right now... but pretty sure after all ;) you are right. I mean, *processContextElement()* is the entry point for the entities creation/update logic, so modification should be done in that part. The **processRegisterContext()** part is for registrations and would remain untouched.

**Comment by arigliano** [comment]
Sorry for the late, the office was closed for a week here for national holidays. I've started to work on the backend layer. In particular, I've created a new function **ensureDateExpirationIndex**, in order to manage the index creation, following a similar approach as for the location index. So I'm modifying the **collectionCreateIndex** function, in order to manage the creation of a TTL index, by using a different version of the **createIndex** function of the mongo driver. In detail, we should pass in an IndexSpec object, which contains the **expireAfterSeconds** option. Once I have finished this part, next step is to manage the value of the particular attribute, in order to parse it as a ISO 8601 date, considering that mongo wants the TTL indexed field as a Date object. In this regard I'm looking for some already existing utility function that does this, that is, parsing from string to ISO8601 dates. The final step should be to call the **collectionCreateIndex** (and a dual function for the index deletion) when creating and updating an entity, in order to manage the transitions from "transient" to "normal", depending on the presence of the specific attribute in the context request.

**Comment by fgalan** [comment]
Documentation regarding this feature in PR https://github.com/telefonicaid/fiware-orion/pull/3220

**Comment by fgalan** [comment]
Implementation in PR #3173

**Comment by fgalan** [comment]
Additional .test in PR https://github.com/telefonicaid/fiware-orion/pull/3230

**Comment by fgalan** [comment]
Some modification on the original implementation (in order to have `dateExpires` as NGSIv2 builtin attribute) in PR https://github.com/telefonicaid/fiware-orion/pull/3240

That's should conclude the implementation of this issue, so I'll close it.
