### ISSUE TITLE
DELETE /v2/registrations/<registrationId> 

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#3006]
implement removal of registrations by registrationId, so that the unregistration of a context source is properly made

**Comment by fgalan** [comment]
Have a look to general comment on the registraitons functionality at https://github.com/telefonicaid/fiware-orion/issues/3008. Many of them could also apply to this issue.

**Comment by fgalan** [comment]
All the registration features share the same common base branch: *feature/ngsiv2_registrations*.

Thus, this issue should be implemented in a branch splited from feature/ngsiv2_regsitrations (instead of master), using the task/ prefix in the new branch name, and the PR done using feature/ngsiv2_registrations as base branch (instead of master).

feature/ngsiv2_registrations will be update regularly with master, to keep it as synced as possible and ease the final feature/ngsiv2_registrations -> master merge once all the NGSIv2 registrations management  functionality gets completed.

**Comment by fgalan** [comment]
Check "MB-27: mongoRegistrationDelete" in flowsIndex.md regarding the diagram (and associated documentation) regarding the operation implemented by this issue.

**Comment by McMutton** [comment]
@fgalan I couldn't find "MB-27: mongoRegistrationDelete" in flowsIndex.md, can you please tell me where can I find it?

**Comment by fgalan** [comment]
Yes... by the moment it is included in a PR mainled aimed at documentation that is pending to land.

Anyway, focus first in the implementation. Let's deal with documentation after all (maybe I can help with that).

**Comment by McMutton** [comment]
Implementation is done, I am now working on the tests. I am going to create the PR tomorrow.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/3145

**Comment by fgalan** [comment]
Devel manual documentation in PR https://github.com/telefonicaid/fiware-orion/pull/3152
