### ISSUE TITLE
CORS support for /version

### ISSUE THREAD

**Issue by aarranz** [telefonicaid/fiware-orion#3066]
Now that the context broker has basic CORS support, would be great to add CORS support to the `/version` API endpoint. This is a very useful API endpoint to know more about the accessed context broker.

**Comment by fgalan** [comment]
@McMutton , what do you think?

**Comment by McMutton** [comment]
At the moment, a good chunk of our CORS logic is in `restReply.cpp` which is independent of the requested resource but only versioned requests are processed (`V1` or `V2`).

So in this case we have two options:

1. We do the required implementation in `restReply.cpp` to process `NO_VERSION` requests as well (not only `/version` but all four of them)

2. We make an exception for /version and put all its CORS logic in `versionTreat.cpp`.

The scope will be bigger but I would go with the first option since in the long term the goal is to have full CORS support for Orion. Second option would be quick but a dirty solution.

**Comment by fgalan** [comment]
`GET /version` is an special operation (e.g. note is the unique operation which renders a JSON in pretty-print format, with newlines and so on) so it wouldn't be problem to implement the exception you mention in alternative 2.

I'd suggest to go for the quick solution and see how it looks like at PR time. In the future we could refactor and going to a more general approach if we need.

**Comment by McMutton** [comment]
Ok @fgalan, makes sense. You can assign this issue to me.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/3142

**Comment by fgalan** [comment]
The implementation has been just merged into master. @aarranz as author of the original issue could you check it works and close the issue, please? Hint: use fiware/orion:latest docker to do the test. Thanks!

**Comment by aarranz** [comment]
It is working as expected when using ngsijs v1.1.0 👍
