### ISSUE TITLE
Silently fails when delete with # in service path

### ISSUE THREAD

**Issue by josubg** [telefonicaid/fiware-orion#3071]
When I try to delete a entity inside a service path and y use  the ending #  in the delete  service path header I received a 204 but the entity is not erased. I tried with the next service paths for  a _\test\testa_ entity:

```
/#
/test/#
/test/testa/#
```

I am using the docker image version of Fiware-orion.

**Comment by fgalan** [comment]
I think this issue is better to be answered as a question in StackOverflow. Could you pleas ask there (just copy-pasting your question) using the "fiware-orion" tag, then add the link to this issue in github, then close the question, pls? Thx!

**Comment by josubg** [comment]
https://stackoverflow.com/questions/48188240/fiware-orion-silently-fails-when-delete-with-in-service-path/48188256#48188256

**Comment by fgalan** [comment]
The question has been answered in SOF.

After answering, I've realized there could be some minor issues related with this. For example, response could be different from 204 and use 400 instead in order the use may know he is using a wrong syntax. However, backward compability implications should be considered.

At least, documentation at https://fiware-orion.readthedocs.io/en/master/user/service_path/index.html could be improved in order to make clearer when `#` and comma-separated lists are allowed for service paths.

Thus, I'm reopening this issue. Thanks for the feedback!

**Comment by josubg** [comment]
Thanks you for the quick response. A 4XX server response would be handy.

**Comment by ArqumFarooqui-NEC** [comment]
Hi @fgalan sir,

As this issue is an old issue, but as per my analysis this issue still need to be fix. So I want to work on this issue.

As per this issue `DELETE` operations with wildcard service path i.e. `#`  and with `comma separated SPs` should not be allowed, currently it is returning `204 No Content`, but it should return following error :
```
    Error :  400 Bad Request
```

```  
    Description : Service path with wildcard # is not allowed in DELETE operation 
    
    Description : More than one service path is not allowed in DELETE  operation

```

As per my analysis, this issue will be fixed in [servicePathCheck()](https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/rest/rest.cpp#L677#L756)  function. After fix, related FTs should also be added.

Please provide your opinion and guidance.
Thank you:)

**Comment by fgalan** [comment]
@ArqumFarooqui-NEC I agree this issue is still valid and with your analysis of it. Thanks for your willingness to work on this!

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/3901
