### ISSUE TITLE
Avoid creating orion database in -multiservice mode

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3179]
No existing Orion databases at starting point:

```
$ echo 'show dbs' | mongo --quiet | grep orion
$
```

Then, start Orion in multiservice mode:

```
$ contextBroker -multiservice
```

After that, `orion` database has been created:

```
$ echo 'show dbs' | mongo --quiet | grep orion
orion       0.000GB
```

It seems this is due to the boostraping logic, which doesn't take multiservice into account and crate the geo-index in `orion`. However, this database is not used in `-multiservice` mode and, for the sake of cleaness, this should be avoided in this case.

**Comment by mathi123** [comment]
@fgalan How would you handle this conceptually?

Proposal:

- Add a startup flag 'autocreatedb' (default = true)
- If this flag is false: dont execute any code to create a database.
- If the flag is true: same path as before

Program execution might fail because a database does not exist. However I see this as expected behavious when the flag is set to _false_? (Db creation is the job for DB admins IMO).

Ps: Do you know of any other operations that require 'admin' privileges, besides db creation?

**Comment by fgalan** [comment]
Actually, Orion doesn't use any *explicit* operation to create database. As far as I know (although my knowledge could be obsolete, as the las time I reviewed database creation aspects was in MongoDB 2.4 :), there isn't any operation to explicitly create databases in mongo: databases are created first time it is used.

However, Orion does an *implicit* creation of database, as it is creates some indexes (for geo-location and TTL functionalities) at startup.

A flag as the one you propose could be added in order to avoid indexes creation in the database. However, this would be dangerous... it could break geo-location of TTL functionalities. But maybe I'm missing something...

Details about mongo startup logic can be found in the code, looking for mongoInit() function. Maybe this can be improved (is a very old piece of code, from the very begning of Orion). Any idea or suggestion about specific changes to do is really welcomed :)

**Comment by Anjali-NEC** [comment]
Hi @fgalan @mathi123 sir,

I am working on this issue and i have raised the PR #3675  for same.
