### ISSUE TITLE
"One shot" subscription

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3189]
It would be great to have some "one shot" subscription mechanism. For instance, the subscription is created with status "oneshot":

```
"status": "oneshot"
```

Once a notification is trigger, the subscription transitions to `"status": "inactive"`. Once in this status, the user may update it with `"oneshot"` (to repeat the same behaviour).

**Comment by fgalan** [comment]
This issue has been asigned to @SourabhChourasiya-NEC

Thanks!

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,
I have successfully implemented the onshot subscription feature at creation time and it is working fine without impacting existing functionalities. 

> It would be great to have some "one shot" subscription mechanism. For instance, the subscription is created with status "oneshot":
> 
> "status": "oneshot"
> Once a notification is trigger, the subscription transitions to "status": "inactive". 

But when I am trying to update the subscription status from inactive to oneshot again through patchSubscription request. I am not getting any notification because initial notification will be sent once we request for new subscription.

> Once in this status, the user may update it with "oneshot" (to repeat the same behaviour).

In this case, I am getting the notification only when someone updates the entity values.

According to my understanding, when someone updates the status of subscription from inactive to oneshot again, a notification will be sent like initial notification or send the current status of the attributes and status again changes to inactive.

**The implementation can be for patchSubscription:**

1. Is there any possibility to repeat the initial notification feature again in case of oneshot subscription ?
2. when a patchSubscription request comes with "status"="oneshot", we delete the exsiting subscription and create a new one so a initial notification will send and status will become inactive again.

Please provide your guidance on above mentioned two possibilities or if you can provide the better way to implement oneshot subscription for update request, it will be very helpful for me.

Thank you

**Comment by fgalan** [comment]
From my point of view, in order to keep things simple and usable, oneshot subscriptions shouldn't trigger initial notification (neither at creation time nor update subscription to move from "inactive" to "oneshot"). Thus, it would be as follows:

* Subscription is created with status "oneshot". No initial notifications is sent.
* Some entity update triggers the subscription. A notification is sent and status passes to "inactive".
* Subscription is update to change status to "oneshot". No initial notification is sent.
* Some entity update triggers the subscription. A notification is sent and status passes to "inactive".
* Subscription is update to change status to "oneshot". No initial notification is sent.
...

From an implementation point of view, I think it should be easy to the status of the subscription at subscription creation or update logic, so initial notification is not triggeed in the case of status == "oneshot".

I hope this feedback may help :) If you have more doubts, don't hesitate to tell me again.

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,
Thank you for your feedback. It was very helpful for me to implement the ONESHOT feature.
I have implemented the ONESHOT subscription feature according to your suggestion.
Currently, I am self-reviewing it. I will raise the PR in 2/3 days.

Should I need to write FT for the same?

Thank You

**Comment by fgalan** [comment]
> Should I need to write FT for the same?

Do you mean functional tests (i.e. .test files)? Yes, every new functionality should come along with corresponding test and documentation.

Thanks!

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,

I have raised the PR #3361 . 
Please review it and guide me further.

Thank You

**Comment by fgalan** [comment]
Thanks for your contribution! I have provided some piece of feedback/question on the PR, as usual :)

**Comment by fgalan** [comment]
PR merged. Closing.
