### ISSUE TITLE
Inconsistency considering percent encoding for attributes' names

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/fiware-orion#3238]
In NGSIv2, spaces cannot be used in attribute's names. Nevertheless, it should be possible to encode spaces using %20. This works correctly as part of entity creations:
```
curl -X POST \
  http://localhost:1026/v2/entities/ \
  -H 'content-type: application/json' \
  -H 'fiware-service: smartgondor' \
  -H 'fiware-servicepath: /gardens' \
  -d '{
  "id": "Room1",
  "type": "Room",
  "temperature%20att": {
    "value": 21,
    "type": "Float"
  },
  "pressure": {
    "value": 711,
    "type": "Integer"
  }
}'
```

Returns `201`.

If I try to query the entity with:

```
curl -X GET \
  http://localhost:1026/v2/entities/Room1 \
  -H 'fiware-service: smartgondor' \
  -H 'fiware-servicepath: /gardens' \
  -d '{
  "id": "Room1",
  "type": "Room",
  "temperature%20att": {
    "value": 21,
    "type": "Float"
  },
  "pressure": {
    "value": 711,
    "type": "Integer"
  }
}'
```

The result is correct:

```
curl -X GET \
  http://localhost:1026/v2/entities/Room1 \
  -H 'cache-control: no-cache' \
  -H 'fiware-service: smartgondor' \
  -H 'fiware-servicepath: /gardens' \
  -H 'postman-token: 9d78f040-52a5-fbd7-69b6-33064ad685c0' \
  -d '{
  "id": "Room1",
  "type": "Room",
  "temperature%20att": {
    "value": 21,
    "type": "Float"
  },
  "pressure": {
    "value": 711,
    "type": "Integer"
  }
}'
```

However, using a request to get the single attribute:

```
curl -X GET \
  http://localhost:1026/v2/entities/Room1/attrs/temperature%20att \
  -H 'cache-control: no-cache' \
  -H 'fiware-service: smartgondor' \
  -H 'fiware-servicepath: /gardens' \
  -H 'postman-token: 3c3bdf11-8ccb-f08a-92c1-beb0b459efc2'
}'
```

The result is: `400 Bad request`
```
{
    "error": "BadRequest",
    "description": "invalid character in URI"
}
```

Another problem happens using `attrs` option:
```
curl -X GET \
  'http://localhost:1026/v2/entities/Room?attrs=temperature%20att' \
  -H 'cache-control: no-cache' \
  -H 'fiware-service: smartgondor' \
  -H 'fiware-servicepath: /gardens' \
  -H 'postman-token: 6fda63f2-4e60-0f40-c213-6650c4ea39fc'
}'
```
Causing the following result:
```
{
    "error": "NotFound",
    "description": "The requested entity has not been found. Check type and id"
}
```

**Comment by fgalan** [comment]
Maybe libcurl (the HTTP server libreary used by Orion) is translaing the %20 into space in the URL before passing it to the CB code...

Could you run Orion in INFO mode (i.e. `-logLevel INFO`) and check the traces for `temperature att` and `temperature%20att` ocurrences, please?

**Comment by fgalan** [comment]
```
msg=Starting transaction from **0.0.0.0:44902/v2/entities/Room1/attrs/temperature att**
```

That's confirm my theory...

Let me think some time to think about this. I'll come back with additional commetns in this issue.

**Comment by fgalan** [comment]
I have checked that the following works:

```
curl -X GET 'http://localhost:1026/v2/entities/Room1/attrs/temperature%2520att' -H 'fiware-service: smartgondor' -H 'fiware-servicepath: /gardens'
```

`%25` is the URL encode for `%` so what it happening here is that `http://localhost:1026/v2/entities/Room1/attrs/temperature%2520att` URL is tranlated to `http://localhost:1026/v2/entities/Room1/attrs/temperature%20att` by libmicrohttpd and offered that way to the Orion logic.

Thus, this is not an actual bug, but a tricky situation that happens when encoding recommendations provided in https://fiware-orion.readthedocs.io/en/master/user/forbidden_characters/index.html are following in URLs. 

As far as I understand, this issue could be solved modifing documentation in two ways:

* Un-recommmend URL encoding as mechanism to encode forbidden chars (at least for fiedls that acts as ids, as entity ids or attribute names)
* Explain the "%25 trick" as solution in the case of using URL encoding

@dcalvoalonso what do you think?

**Comment by dcalvoalonso** [comment]
I agree with both points @fgalan :)

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/3278
