### ISSUE TITLE
Accumulator Server - adding proxy functionality

### ISSUE THREAD

**Issue by szymonCaban** [telefonicaid/fiware-orion#3239]
Is there a possibility of adding proxy functionality to accumulation server? Or just adding simple proxy server to scripts? Proxy server which can be run on whatever ip addr we want matters great deal, because it resolves issues that are described [here](https://stackoverflow.com/questions/49458811/accumulation-server-no-action/51266109#51266109) and [here](https://stackoverflow.com/questions/51022502/no-connection-between-freeboards-data-source-for-orion-and-context-broker). The only purpose of proxy server is to:

1. have an endpoint for connections coming from outside (in my situation those would be queries for JSON send from Freeboard) and sending back JSON data payload which are described in 2nd point
2. have a possibility of quering for context to Orion Context Broker on a trigger of receiving query request from outside source (in this case Freeboard) and sending further data received from OCB as told in 1st point.

The issue is that I can not communicate from Freeboard with Orion Context Broker and having that proxy resolves those issues. It kinda ruins the experience of interacting with Context Broker, but in architecture situation that I'm in right now (running OCB as a docker container on host which is a LUbuntu VM) I don't have any better options. Regular running OCB as it suppose to be run is impossible. 

I'm planning to try to write that proxy "server" however if there are better ideas or methods of resolving this, they will be appreciated.

**Comment by fgalan** [comment]
accumulstor-server.py is mainly thougth as a functional test helper (acting as mock in some of the use cases covered by these tests) and for tutorials (the API walkthrough in documentation). No sure if it should grow in that direction... maybe there are out-of-box software pieces out there implement what you want (transparent proxy, I guess).

However, in order to get a more precise idea of what you are proposing, could you add an architecture diagram in a new comment in this issue in order to see what you mean? Ideally, one diagram showing you current situation (with the problem), and a second diagram showsing how the proxy solves the case. Thanks!

**Comment by szymonCaban** [comment]
The overview for now is looking like this and is described in links attached in previous comment. To put it simply, Freeboard can not access OCB from the Browser. It's not the Browser fault, because I can simply put 

        http://orionHost:port/v2/entities/entityId

in url-bar and will receive JSON payload that I want to get. I reported the issue with Freeboard, but on their side there is no support whatsoever so it needs to be coped with at least temporarily 

![image](https://user-images.githubusercontent.com/32677342/42519207-c66c2c74-8463-11e8-8acf-120f12ca0306.png)

I tried to host docker in many other ways, on physical ip, and so on. Only hope that I found in my situation is that while accumulator server couldn't communicate with OCB while acc. was run on localhost, it could whilst run on physical interface. 

Then the proxy came in place, I tried already one server running on physical interface and it was detected by Freeboard's datasources. There was an [issue](https://github.com/Freeboard/freeboard/issues/208) in Freeboard's github repo that indicated some solution and it corresponded to problems that I endured. 

My solution (it might be an over the top approach) is presented here:
![image](https://user-images.githubusercontent.com/32677342/42519765-0b28cd08-8465-11e8-976f-13d09f534fba.png)
The OCB parameters will be defined before starting proxy server. 
In step one, request for data is send from Freeboard with accesible proxy-server ip, then in 2nd step the resource indicator part from URL is taken and parsed onto query for data send to OCB. Then data is received in proxy and send to Freeboard. If written properly proxy can even parse requests from FIWARE Orion Data Plugin for Freeboard, however that plugin is using v1 query method with payload in request so it will be probably too much of a hustle. For now simple JSON requests from Freeboard will be availible for querying data from OCB and visualizing them. I just don't wanna wast the potential of easy visualisation context data.

**Comment by fgalan** [comment]
Thank you for so detailed explanation.

In general lines (and taking into account that I may be wrong, because I'm not on it as you are :), I think your approach to use a proxy in the middle of Freeboard and Orion is a good idea. However, I don't get the point about modifying accumulator-server.py in order to play the role of a proxy. From my point of view, you should use a separate piece of sofwater, either:

* Using some general purpose proxy software. Not sure, but maybe ngix could do the trick-
* Using some Orion-specific proxy . It seems there are some project out there related with that, as https://github.com/inter-coder/Orion-Web-Proxy-for-Cross-Domain or https://github.com/nmerinos/ProxyOrionContextBroker although I don't know if they are currently mantained (I haven't used them).
* Using a simple proxy written by you. It should be pretty easy in languages Node.js or Python.

@jmcanterafonseca maybe could provide additional feedback. Not sure, but I think he was playing with Orion proxies in the past.

**Comment by szymonCaban** [comment]
After studying delivered sourced I decided on writing proxy myself. It was a python proxy server using Flask, if someone would be interested, there is the code of it:

```from flask import Flask
from flask import jsonify
from flask_cors import CORS #most important thing here
import requests
import json

app = Flask(__name__)
#making the server suitable for our purpose = making it cross domain friendly
CORS(app)

#http://flask.pocoo.org/docs/0.12/quickstart/  - on Flask and modifying routes

@app.route('/<entityId>', methods=['GET'])

#redirecting request coming from Freeboard which was sent on: 
#http://127.0.0.1:9090/entityId
#where first part of URL specifies address and port that proxy is run on (app.run) 
#part after last slash specifies entityId that we want to get information about

def askOrion(entityId):
 	#URL to communicate with OCB on
 	url = 'http://127.0.0.1:1026/v2/entities/' + entityId
 	r = requests.get(url)
 	return jsonify(r.json())

if __name__ == '__main__':
	app.run(host='127.0.0.1', port='9090')
```

After running it in same environment as Orion Context Broker and Freeboard, it works like a charm. 

However! I've been looking for some materials on Context Management Architecture in FIWARE GEs, and came across article showing [CORS SUPPORT FOR ORION CONTEXT BROKER](https://www.fiware.org/2015/05/27/cors-support-for-orion-context-broker/). I mean it's the simplest way of dealing with the situation that I described. Just a shame that I needed to dig so deep to make things work. In my opinion the CORS option should be surely more visible in documentation or some walkthroughs. Throwing `-corsOrigin __ALL -corsMaxAge 600` as describer [here](https://fiware-orion.readthedocs.io/en/master/user/cors/index.html) at the end of docker's starting command for Broker (in my case) will be a miracle worker. 

I will push this answer simultaneously to stack overflow, because it will be helpful for someone who want's to use dashboards or some other front-endy apps running in browsers in connection with OCB.

**Comment by fgalan** [comment]
Thanks for the detailed feedback and the in-issue code contribution!

I'm sorry you find the easy solution after walking by the hard way :( I'll move the "CORS" section above in the left-panel index, just after Pagination in order to make it more visible so other users don't have the same problem in the future.

**Comment by fgalan** [comment]
PR with doc modification: https://github.com/telefonicaid/fiware-orion/pull/3274

Please close the issue if nothing else need to be done. Thanks!
