### ISSUE TITLE
Add script to build the Context Broker Driver updated in scripts/build

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-orion#3268]
Add script to build the Context Broker Driver updated in scripts/build

Separate script to only manual build
And/or call to this script from "timestampVersion.sh"

**Comment by fgalan** [comment]
The idea could make sense. However, note that Orion depends of several third party software appart from the mongodb driver (see https://fiware-orion.readthedocs.io/en/master/admin/build_source/index.html). Thus, why limit the script to mongo driver instead of taking into account all the dependencies?

Moreover, the script is already done. In some way, "embedded" insisde the Dockerfile at https://github.com/telefonicaid/fiware-orion/blob/master/docker/Dockerfile. Maybe we should "extract" from it (and avoid duplicating the same scrtip, both in Dockerfile and in a separate file).

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I would like to work on this issue. As per my understanding we need to write a script for upgrading version of all the dependencies in case of manual build installation of contextBroker. Please confirm my understanding and assign this issue to me.

Thanks

**Comment by fgalan** [comment]
Not sure if this issue is obsolete (note it was created almost 3 year ago). Let's wait for @cesarjorgemartinez (as original author of the issue) to confirm if it is still valid or not and, in the former case, which specific task has to be done.

**Comment by Anjali-NEC** [comment]
Hi @cesarjorgemartinez Please confirm this issue is still need to be fixed?

**Comment by fgalan** [comment]
We have been discussing internally and this issue probably no longer makes sense. Thus, it is going to be closed.

Anyway thanks @Anjali-NEC for your willingness to work on this. Maybe you could look for another issue to work on it! :)
