### ISSUE TITLE
How to unsubscribe particular entity from csubs using subscribe_id

### ISSUE THREAD

**Issue by janaka1984** [telefonicaid/fiware-orion#3369]
Hi @fgalan ,

i couldn't find particular **subscribe_id** to **unsubscribe** particular entity from **csubs**.

If i can use customize  **subscribe_id**  instead of auto **generate id**, it is easy to unsubscribe particular id. 
But i couldn't set customize id, when call **subscribe(self, entity_id, entity_type="openmtc", fiware_service="")** in **orion_api.py**

Regards
Janaka

**Comment by fgalan** [comment]
This is more a question about functionality rather than an actual issue in Orion code. Thus, I'd suggest to move it to StackOverflow (https://www.stackoverflow).

Thus, could you please create a question post in SOF, please? It would be just a matter of copy-pasting the same text, so it should be easy :) Please, don't forget to include the "fiware-orion" label.

Once done, please add the link to the question as comment in this issue for traceability. Then, close the issue.

Thanks!

**Comment by janaka1984** [comment]
Hi @fgalan 

Thanks for reply
I have added above question to SOF
https://stackoverflow.com/questions/53629748/how-to-unsubscribe-particular-entity-from-csubs-using-subscribe-id-in-fiware-ori

Regards
Janaka
