### ISSUE TITLE
Strange behavior in PATCH /v2/entities

### ISSUE THREAD

**Issue by jmezzera** [telefonicaid/fiware-orion#3640]
Problem described in [SOF](https://stackoverflow.com/questions/60660119/is-there-a-way-to-patch-to-an-entity-using-wildcards-or-list-of-servicepaths). 

Maybe I'm doing something wrong, however I'm getting a 204 when the query did not work and I think that's not right. 

Thoughts?

**Comment by fgalan** [comment]
With regards to the question in SOF, it understand it has been already nicely anwered by @kzangeli (please, tell me otherwise).

However, there is probably an issue in Orion to be solved. In particular:

* PATCH without service path returns 200. "Without service paths" defaults to `/` in updates requests (as PATCH is). If the entity doesn't exist previously in `/`, then this is a bug (a 404 should be returned). Need to be checked (the SOF question doesn't clarify if the entity previously exists or not)
* PATCH with service path wildcards (i.e. `#`) returns 204. It should return 400.

My last try was to use a list of known SPs: I know the entity I want is in one of a number of SPs, so a used a comma separated list as the SP header. Same as above: 204 but no change.

**Comment by fgalan** [comment]
Thanks for the feedback @jmezzera !

**Comment by jmezzera** [comment]
The question was kind of resolved In SOF. I'm afraid I did not fully understand it o maybe is the -possible- underlying  issue we are discussing here. 

Concretely: Is it possible to PATCH an entity with a wildcard in the SP? Take this for example:
```
/ID1
/group2/ID2
/group1/ID3
```

* `PATCH /ID1 with SP /` works
* `GET  /ID3 without SP` works
* `PATCH /ID3 with SP /group1` works (204 and updates)
* `PATCH /ID3 without SP` does not work (404) 
* `PATCH /ID3 with SP /#` does not work but returns ok (204 but no update). 
* `PATCH /ID3 with SP /group1, /group2` same as above: 204 and no update)

In these two cases, I'm not sure what the expected behavior is (definitely not the 204 and no update). In my opinion, it would be nice that if (and only if) the query is not ambiguous, the entity should be updated. Any other case, a 404 should be raised. 

Hope this helps.

**Comment by jmezzera** [comment]
Hi. Was anyone able to replicate the issue? 
Don't hesitate to ask me for further information.

**Comment by fgalan** [comment]
> 
> 
> Hi. Was anyone able to replicate the issue?
> Don't hesitate to ask me for further information.

I haven't tried myself, but I think the information above in this issue is complete enough to guide a developer to fix this issue. Thanks!

To be clear with the scope: the scope of this issue is about fixing the response codes (currently wrongly using 2xx) for some error conditions. The support of wildcards and/or comma separate lists in fiware-servicepath is not in the scope of this issue (if that is required, then I'd suggest to open a new issue, about "Multi-update entities in several service paths" or similar).

**Comment by fgalan** [comment]
> PATCH without servicepath and if entity doesn't exist, returning 404. So no need to do anything.
> PATCH with servicepath #, returning 204, It should return 400. PR #3812 has been raised to fix this.
> PATCH with multiple servicepath, returning 204, It should return 400. PR #3812 has been raised to fix this.

It would be great if you could include in the PR functional tests (i.e. .test files) to cover these behaviours. Thanks!
