### ISSUE TITLE
How to send measure from orion to iotagent-LoRaWAN?

### ISSUE THREAD

**Issue by Anjali-NEC** [telefonicaid/fiware-orion#3807]
Hi Team,

I want to send measures from fiware-orion to iot-agent LoRaWAN(SOUTHBOUND TRAFFIC)

I've done the device provisioning properly and also verify NORTHBOUND TRAFFIC by sending the measures from iotagent-LoRaWAN to orion through thethingsnetwork.

Please guide me on this. Thanks.

**Comment by fgalan** [comment]
This seems to be a question on functionality rather than an issue with the software. Thus, it would be better to post it at https://stackoverflow.com. Could you do that, please? Use the "fiware-orion" label.

After that, include the link to the SOF question as a comment in this issue. Then, close this issue.

Thanks!

**Comment by Anjali-NEC** [comment]
Added issue at https://stackoverflow.com/questions/66597353/fiware-iotagent-lorawan-how-to-send-measure-from-orion-to-lorawan
