### ISSUE TITLE
How to pass the authentication of http at the registrationsAPI

### ISSUE THREAD

**Issue by ryo-ma** [telefonicaid/fiware-orion#3885]
What I set when the provider Orion is being authenticated?
Can I use `httpCustom` like the one below?

```bash
curl localhost:1026/v2/registrations  -d @-  <<EOF
{
  "dataProvided": {
    "entities": [
      {
        "id": "xxxxx*",
        "type": "XXXXXX"
      }
    ]
  },
  "provider": {
    "http": {
      "url": "https://<orion-endpoint>"
    }
  },
  "httpCustom": {
    "headers": {"Authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
  }
}
```

**Comment by fgalan** [comment]
Orion uses the same `x-auth-token` in the forwarded request than in the original client request (see for instance https://github.com/telefonicaid/fiware-orion/blob/master/test/functionalTest/cases/0715_forward_xauth_token_to_cprs/propagate_xauth_token_for_update_and_query_standard_ops.test). 

That means that FIWARE-based authentication (based in Keystone IDM) can work with registrations/CPrs. However, other forms of authentication (like a custom "Authorization" header) are not supported in this case. The `httpCustom` element is only supported in subscriptions but not in registrations.

**Comment by ryo-ma** [comment]
What are your thoughts on context data collaboration in multiple cities(multiple vendors)?
I thought it would be possible with the registration API. However, it was difficult to realize due to authentication problems.

Also, do you plan to implement `httpCustom` with the registration API in the future?

**Comment by fgalan** [comment]
> What are your thoughts on context data collaboration in multiple cities(multiple vendors)?
> I thought it would be possible with the registration API. However, it was difficult to realize due to authentication problems.

I understand you are referring to a *context federation* scenario. Federation could be based in registrations/CPrs (we name it "pull" federation) or in subscriptions/notifications (we name it "push" federation). The former is described in this document https://fiware-orion.readthedocs.io/en/master/user/federation/index.html and maybe suffices your use case better than using registrations/CPrs.

> Also, do you plan to implement `httpCustom` with the registration API in the future?

It is not in our roadmap but of course we are open to contributions in the case you or your team want to develop it. Anyway instead of using a new `httpCustom` field in registrations, maybe a better alternative is to include in the forwarded request the same headers than in the original request (except the ones to which Orion pay especial treatment, if any). It seems a more flexible alternative.

**Comment by ryo-ma** [comment]
OK. I got it!
