### ISSUE TITLE
Orion HTTPS with Cert and Priv Key from GoDaddy

### ISSUE THREAD

**Issue by ddigodavid** [telefonicaid/fiware-orion#4012]
Hi @fgalan !
 
I’m Rodrigo, CTO at [The Helix Platform](gethelix.com.br), I work with Fabio Cabrini. He told me you know each other!
We are currently entering in production with a new customer, but I headed up into a problem with Orion Context Broker.
 
We have a wildcard cert from GoDaddy but the cert exported has exactly 2350 bytes. The problem is that in Orion has limited the cert and priv key size to 2048 bytes.
 
Would you help us with this problem? We have a deadline coming up, and that’s the only issue we currently have. Everything is working perfectly, except from the Orion HTTPS mode.
 
![image](https://user-images.githubusercontent.com/17949752/144304546-e89139f0-acb6-46a2-a36a-22b227a33b90.png)

Best regards,
Rodrigo D. Oliveira

**Comment by mapedraza** [comment]
Hi @ddigodavid, thanks for reporting the Issue.

@kzangeli from FIWARE foundation sent me via Skype a possible fix. I just uploaded the changes in a new branch and created a new PR #4014. How ever, It needs to be reviewed, tested, documented and so on. 

Since it is an urgent topic I would suggest you to check if using a reverse proxy (like NGINX, check [this link](https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/)) in front of Orion could work.

**Comment by fgalan** [comment]
> We have a wildcard cert from GoDaddy but the cert exported has exactly 2350 bytes. The problem is that in Orion has limited the cert and priv key size to 2048 bytes.

What about asking for a shorter certificate? If you are a paying customer of GoDaddy they should support your request of shorter certs ;)

**Comment by kzangeli** [comment]
This was a mistake in the initial implementation (**my mistake**). Let's just fix it. It's easy enough

**Comment by ddigodavid** [comment]
> > We have a wildcard cert from GoDaddy but the cert exported has exactly 2350 bytes. The problem is that in Orion has limited the cert and priv key size to 2048 bytes.
> 
> What about asking for a shorter certificate? If you are a paying customer of GoDaddy they should support your request of shorter certs ;)

@fgalan I cant, every options in their platform gives me this certificate with 2350 bytes.



> This was a mistake in the initial implementation (**my mistake**). Let's just fix it. It's easy enough

Thanks, @kzangeli !! 🙏

**Comment by ddigodavid** [comment]
> Hi @ddigodavid, thanks for reporting the Issue.
> 
> @kzangeli from FIWARE foundation sent me via Skype a possible fix. I just uploaded the changes in a new branch and created a new PR #4014. However, It needs to be reviewed, tested, documented, and so on.
> 
> Since it is an urgent topic I would suggest you to check if using a reverse proxy (like NGINX, check [this link](https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/)) in front of Orion could work.

Thanks @mapedraza !! I'll try it! ;))

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/4014

@ddigodavid the fix will be included in the next Orion release (3.5.0) but it the meanwhile you can get if from dockerhub build from master branch. In theory that should be `fiware/orion:latest` but it seems there is some problem with that image (see https://github.com/telefonicaid/fiware-orion/issues/4028). FIWARE Foundation (the owners of fiware dockerhub organization) has been reported... you should contact them to get any further support regarding the docker image.

**Comment by ddigodavid** [comment]
Thanks!! @fgalan @mapedraza

**Comment by fgalan** [comment]
> Thanks!! @fgalan @mapedraza

Thanks also to @kzangeli that did the fix ;)
