### ISSUE TITLE
Release 3.7.0 tag is missing on docker hub

### ISSUE THREAD

**Issue by Siedlerchr** [telefonicaid/fiware-orion#4154]
**Bug description**

I wanted to test version 3.7.0, however on docker hub there is no release tagged with 3.7.0. I only find releases tagged with 3.70-PRE
https://hub.docker.com/r/fiware/orion/tags?page=1&name=3.7

**Comment by fgalan** [comment]
Not sure why it's not working... @wistefan could you have a look, please?

In the meanwhile, you can use `telefonicaiot/fiware-orion:3.7.0`

**Comment by Siedlerchr** [comment]
It's still not there... But the the telefonicaiot/fiware-orion:3.7.0 worked

**Comment by fgalan** [comment]
Great!

Based on the feedback, I'll close the issue. However, please feel free of contacting FIWARE Foundation (@wistefan @jason-fox ...) regarding the sync problems in fiware dockerhub organization.

**Comment by jason-fox** [comment]
Since Docker removed the ability for a third-party to listen to releases and automate builds, the `fiware` docker tags will always lag the original source of truth. `telefonicaiot` needs to build and tag first, `fiware` is just an aggregator of existing images.   This  is the case `telefonicaiot`, but it is also true for all other components aggregated from the FIWARE Catalogue. The only time that the latest `telefonicaiot` tag can be assured to be duplicated on the `fiware` account is just prior to an umbrella FIWARE release.

Anyway I pushed off a sync process and `fiware/orion:3.7.0` can also be used at this point.

**Comment by Siedlerchr** [comment]
@jason-fox  Thanks! Can you check the same for the ging/fiware-idm and ging/fiware-pep 
https://github.com/ging/fiware-pep-proxy/issues/141

**Comment by fgalan** [comment]
> Since Docker removed the ability for a third-party to listen to releases and automate builds, the `fiware` docker tags will always lag the original source of truth. `telefonicaiot` needs to build and tag an image first, `fiware` is just an aggregator of existing Docker images. This is the case for `telefonicaiot`, but it is also true for all other components aggregated from the FIWARE Catalogue. The only time that the latest `telefonicaiot` tag can be assured to be duplicated on the `fiware` account is just prior to an umbrella FIWARE release.

If fiware dockerhub cannot keep sync with the "sources of truth" :), maybe fiware dockerhub organization should be disabled. Otherwise, we will have more issues like the one that @Siedlerchr reports here, causing confusion in our users.
