### ISSUE TITLE
Docker Image for Version 3.12.0 Missing on DockerHub and Quay.io

### ISSUE THREAD

**Issue by goten002** [telefonicaid/fiware-orion#4551]
**Bug description**
The latest version 3.12.0 of FIWARE Orion is not available on DockerHub or Quay.io. The latest available image is for version 3.11.0, only pre-release images (3.12.0-PRE-xxx) are available, but the final release image for 3.12.0 is missing.

- Orion version: 3.12.0
- MongoDB version: N/A
- Env variables or CLI parameters: N/A
- Operating System or Docker Image used: Docker

**Comment by fgalan** [comment]
You can get Orion 3.12.0 at `telefonicaiot/fiware-orion:3.12.0 (see https://hub.docker.com/r/telefonicaiot/fiware-orion/tags)

We don't maintain images at DockerHub FIWARE organization (https://hub.docker.com/u/fiware) or Quay.io. Maybe somebody from the FIWARE Foundation (CC: @jason-fox ) can explain better the situation there.

**Comment by goten002** [comment]
I appreciate the clarification regarding the maintenance of images.

Thanks very much for your assistance and your prompt response!

**Comment by jason-fox** [comment]
FIWARE should only be publishing tagged releases (and not `-PRE` releases) as a convenience copy of the `telefonicaiot/fiware-orion`docker repository. I never really understood why FIWARE was tracking `-PRE` releases for Orion (and Orion only). I guess this is something that had been happening since FIWARE began.

Tags for `quay.io/fiware/orion:3.12.0` on quay.io and `fiware/orion:3.12.0` on DockerHub are now available . DockerHub have slowly been removing free functionality for Open Source projects over the years in an attempt to increase revenue, so FIWARE is copying to multiple places for the time being.  Bleeding edge remains `telefonicaiot/fiware-orion` of course, which is under the control of the Telefónica team.

**Comment by fgalan** [comment]
`telefonicaiot/fiware-orion` is not only for the bleeding edge (`:latest`) but also holds tagged releases (`:3.12.0`, etc.).

Just to make it clear... :)
