### ISSUE TITLE
Release mongo connection in unit_test

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#933]
The function mongoInitialConnectionGetForUnitTest() gets a connection for unit tests (in the function setupDatabase in testInit.cpp).
Unfortunately, we don't give this connection back. There is no function that we call after using the connection where we could release the connection (this all woeked differently before implementing the connection pool).

We could use utInit/utExit for getting/releasing the connection but we'd want that to depend on a parameter for utInit - we don't need a mongo connection for all unit tests - far from it.

utInit(bool getConnection);
utExit(bool releaseConnection);

utInit/utExit should be called by EVERY unit_test and the resources the unit_test needs should all be input to utInit (and utExit).

Let's start with the mongo connection for now, as it is giving us problems.

**Effort: 5 man day**

**Comment by fgalan** [comment]
I think that get/release of the connection works ok, as the pool is started (we have a mongoStart() call in setupDatabase() which use a static boolean to ensure it is called one time at the begining of the tests).

The only problem that I recently found in a PR (see https://github.com/telefonicaid/fiware-orion/pull/977) was related with the setupDatabase, where I need to add a releaseMongoConnection() call (see https://github.com/telefonicaid/fiware-orion/commit/f901c2d2e9f5d3221a656f0e37c0bfccd11fbe27#diff-00bc2266723cb96df06c44db05f4e761R68). Otherwise some unit test fails in the middle due to it isn't any free connection in the pool.

Maybe after that fix everything is ok and this issue may be closed?

**Comment by kzangeli** [comment]
Yes, I think it can be closed
